# @generated by datamodel-codegen:
#   filename:  adapter-protocol-v3.schema.json

from enum import StrEnum
from typing import Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AdapterErrorCode(StrEnum):
    invalid_request = 'invalid_request'
    unsupported_protocol_version = 'unsupported_protocol_version'
    invalid_settings = 'invalid_settings'
    internal = 'internal'
    unsupported_operation = 'unsupported_operation'


class BenchDefinitionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int, Field(ge=0)]
    reset_prefix_cache: bool = False
    seed: Annotated[int, Field(ge=0)]
    temperature: float
    timeout_seconds: Annotated[int, Field(ge=0)]


class BenchLoadInputConcurrencyLimited(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int, Field(ge=0)]
    kind: Literal['concurrency_limited'] = 'concurrency_limited'


class BenchLoadInputRequestRateLimited(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    burstiness: float | None = None
    kind: Literal['request_rate_limited'] = 'request_rate_limited'
    request_rate: float


class BenchLoadInputUnboundedRequestRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['unbounded_request_rate'] = 'unbounded_request_rate'


class BenchLoadInput(
    RootModel[
        BenchLoadInputConcurrencyLimited
        | BenchLoadInputRequestRateLimited
        | BenchLoadInputUnboundedRequestRate
    ]
):
    root: Annotated[
        BenchLoadInputConcurrencyLimited
        | BenchLoadInputRequestRateLimited
        | BenchLoadInputUnboundedRequestRate,
        Field(description='How a Bench case paces its requests.'),
    ]


class CaptureControlRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    start_path: str
    stop_path: str


class CaptureTargetRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    control: CaptureControlRequirement


class ClientStatus(StrEnum):
    succeeded = 'succeeded'
    failed = 'failed'


class EndpointAssignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: str
    port: Annotated[int, Field(ge=0, le=65535)]


class EndpointProtocol(RootModel[Literal['http']]):
    root: Annotated[
        Literal['http'],
        Field(description='The application protocol a workload endpoint speaks.'),
    ] = 'http'


class EvalDefinitionInputOpenaiSmoke(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['openai_smoke'] = 'openai_smoke'
    max_tokens: Annotated[int, Field(ge=0)]
    prompt: str
    timeout_seconds: Annotated[int, Field(ge=0)]


class EvalDefinitionInputLmEval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int | None, Field(ge=0)] = None
    dataset: str | None = None
    few_shot: Annotated[int | None, Field(ge=0)] = None
    kind: Literal['lm_eval'] = 'lm_eval'
    limit: Annotated[int | None, Field(ge=0)] = None
    max_tokens: Annotated[int | None, Field(ge=0)] = None
    metric: str
    seed: Annotated[int | None, Field(ge=0)] = None
    split: str | None = None
    task: str
    threshold: float
    timeout_seconds: Annotated[int, Field(ge=0)]


class EvalDefinitionInput(
    RootModel[EvalDefinitionInputOpenaiSmoke | EvalDefinitionInputLmEval]
):
    root: Annotated[
        EvalDefinitionInputOpenaiSmoke | EvalDefinitionInputLmEval,
        Field(
            description='The measurement an Eval client runs against the workload endpoint.'
        ),
    ]


class HttpMethod(RootModel[Literal['post']]):
    root: Annotated[
        Literal['post'], Field(description='The HTTP method of an [`HttpActionSpec`].')
    ] = 'post'


class IntegrationIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapter_id: str
    adapter_version: str
    framework: str


class KvTransferMechanism(StrEnum):
    mooncake = 'mooncake'
    nixl = 'nixl'


class ParallelismAttention(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context_parallel_size: Annotated[int | None, Field(ge=1)] = None
    data_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ParallelismExperts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_parallel_size: Annotated[int | None, Field(ge=1)] = None
    dense_tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None
    expert_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ParallelismOuter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pipeline_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ProcessSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: list[str]
    env: dict[str, str]


class ProtocolVersion(RootModel[Literal['3']]):
    root: Annotated[
        Literal['3'],
        Field(
            description='The adapter protocol version an integration speaks. The only accepted value\nis `3` (serialized as the string `"3"`); a mismatch is rejected before\nlowering.'
        ),
    ] = '3'


class PublicEndpointRequirementReplica(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['replica'] = 'replica'
    replica_id: str


class RawArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: str
    name: str
    path: str


class ReadinessProbeHttp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['http'] = 'http'
    path: str


class ReadinessProbeProcessAlive(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['process_alive'] = 'process_alive'


class ReadinessProbe(RootModel[ReadinessProbeHttp | ReadinessProbeProcessAlive]):
    root: Annotated[
        ReadinessProbeHttp | ReadinessProbeProcessAlive,
        Field(description='How the control plane decides a process is ready.'),
    ]


class RenderedServeProcess(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    process: ProcessSpec


class ServeModelInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locator: str
    served_name: str


class Device(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class ServeProcessAllocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    devices: list[Device]
    endpoint: EndpointAssignment
    machine_id: str
    model_locator: str
    ports: dict[str, EndpointAssignment]
    process_id: str
    rank: Annotated[int, Field(ge=0)]
    replica_id: str
    replica_index: Annotated[int, Field(ge=0)]
    role_id: str
    runtime_cache_root: str


class ServeReplicaRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accelerator_count: Annotated[int, Field(ge=0)]
    capture_target: CaptureTargetRequirement | None = None
    id: str
    ports: list[str]
    primary_ports: list[str]
    primary_readiness: ReadinessProbe
    replica_index: Annotated[int, Field(ge=0)]
    role_id: str
    worker_readiness: ReadinessProbe


class ServeRoleKind(StrEnum):
    serve = 'serve'
    prefill = 'prefill'
    decode = 'decode'
    router = 'router'


class ServeRoleLinkRequestRouting(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['request_routing'] = 'request_routing'
    source: str
    targets: list[str]


class ServeRoleLinkKvTransfer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['kv_transfer'] = 'kv_transfer'
    mechanism: KvTransferMechanism
    source: str
    target: str


class ServeRoleLinkBootstrap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['bootstrap'] = 'bootstrap'
    port: str
    source: str
    target: str


class ServeRoleLinkSideChannel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['side_channel'] = 'side_channel'
    port: str
    source: str
    target: str


class ServeRoleLink(
    RootModel[
        ServeRoleLinkRequestRouting
        | ServeRoleLinkKvTransfer
        | ServeRoleLinkBootstrap
        | ServeRoleLinkSideChannel
    ]
):
    root: Annotated[
        ServeRoleLinkRequestRouting
        | ServeRoleLinkKvTransfer
        | ServeRoleLinkBootstrap
        | ServeRoleLinkSideChannel,
        Field(
            description='A directed link between serve roles the integration declares as part of the\ntopology.'
        ),
    ]


class ServeTopology(StrEnum):
    single = 'single'
    prefill_decode = 'prefill_decode'


class SettingValue(
    RootModel[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]]
    ]
):
    root: Annotated[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]],
        Field(
            description='A framework-specific server setting value carried as structured JSON data\n(never a pre-rendered shell fragment) across the integration boundary.'
        ),
    ]


class AdapterError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: AdapterErrorCode
    message: str


class AdapterResponseError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: AdapterError
    protocol_version: ProtocolVersion
    status: Literal['error'] = 'error'


class BenchCaseInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    load_shape: BenchLoadInput
    request_count: Annotated[int, Field(ge=0)]


class BenchClientResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed_requests: Annotated[int, Field(ge=0)]
    error: str | None = None
    failed_requests: Annotated[int, Field(ge=0)]
    metrics: dict[str, float]
    native_command: list[str]
    native_exit_code: int | None = None
    normalization_schema: str
    raw_artifacts: list[RawArtifact]
    schema_version: Annotated[
        int,
        Field(
            description='Result envelope version; clients write `1`. The measurement runtime\nrejects a bench result whose version is not `1`.',
            ge=0,
        ),
    ]
    status: ClientStatus


class ClientEndpointInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_path: str
    host: str
    port: Annotated[int, Field(ge=0, le=65535)]
    protocol: EndpointProtocol


class EvalClientRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    definition: EvalDefinitionInput
    endpoint: ClientEndpointInput
    model: ServeModelInput
    protocol_version: ProtocolVersion


class EvalClientResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str | None = None
    metrics: dict[str, float]
    native_command: list[str]
    raw_artifacts: list[RawArtifact]
    schema_version: Annotated[
        int,
        Field(
            description='Result envelope version; clients write `1`. The measurement runtime\nrejects an eval result whose version is not `1`.',
            ge=0,
        ),
    ]
    status: ClientStatus


class HttpActionSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: HttpMethod
    path: str


class Parallelism(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attention: Annotated[
        ParallelismAttention | None, Field(description='Attention-block parallelism.')
    ] = None
    experts: Annotated[
        ParallelismExperts | None, Field(description='MoE expert parallelism.')
    ] = None
    outer: Annotated[
        ParallelismOuter | None,
        Field(
            description='Outer deployment parallelism shared by attention and experts.'
        ),
    ] = None


class PublicEndpointRequirementBuiltinProxy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decode_role: str
    kind: Literal['builtin_proxy'] = 'builtin_proxy'
    prefill_role: str
    process_id: str
    readiness: ReadinessProbe
    role_id: str


class PublicEndpointRequirement(
    RootModel[PublicEndpointRequirementReplica | PublicEndpointRequirementBuiltinProxy]
):
    root: Annotated[
        PublicEndpointRequirementReplica | PublicEndpointRequirementBuiltinProxy,
        Field(description="How the topology's public workload endpoint is exposed."),
    ]


class RenderServeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    integration: IntegrationIdentity
    processes: list[RenderedServeProcess]


class ServeRoleInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: ServeRoleKind
    parallelism: Parallelism
    replica_count: Annotated[int, Field(ge=0)]
    settings: dict[str, SettingValue]


class ServeRoleResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effective_parallelism: Parallelism
    effective_settings: dict[str, SettingValue]
    id: str
    kind: ServeRoleKind
    replica_count: Annotated[int, Field(ge=0)]


class AdapterResultRenderServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Literal['render_serve'] = 'render_serve'
    output: RenderServeResult


class BenchClientRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    case: BenchCaseInput
    definition: BenchDefinitionInput
    endpoint: ClientEndpointInput
    model: ServeModelInput
    protocol_version: ProtocolVersion


class EndpointRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    api_path: str
    prefix_cache_reset: HttpActionSpec | None = None
    protocol: EndpointProtocol


class PlanServeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kv_transfer: KvTransferMechanism | None = None
    model: ServeModelInput
    parallelism: Parallelism
    profiling: bool = False
    roles: list[ServeRoleInput]
    routing_backend: str
    settings: dict[str, SettingValue]
    topology: ServeTopology


class PlanServeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effective_parallelism: Parallelism
    effective_settings: dict[str, SettingValue]
    endpoint: EndpointRequirement
    integration: IntegrationIdentity
    links: list[ServeRoleLink]
    public_endpoint: PublicEndpointRequirement
    replicas: list[ServeReplicaRequirement]
    roles: list[ServeRoleResult]


class RenderServeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allocations: list[ServeProcessAllocation]
    kv_transfer: KvTransferMechanism | None = None
    links: list[ServeRoleLink]
    model: ServeModelInput
    parallelism: Parallelism
    profiling: bool = False
    roles: list[ServeRoleResult]
    routing_backend: str
    settings: dict[str, SettingValue]
    topology: ServeTopology


class AdapterRequestPlanServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: PlanServeInput
    operation: Literal['plan_serve'] = 'plan_serve'
    protocol_version: ProtocolVersion


class AdapterRequestRenderServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: RenderServeInput
    operation: Literal['render_serve'] = 'render_serve'
    protocol_version: ProtocolVersion


class AdapterRequest(RootModel[AdapterRequestPlanServe | AdapterRequestRenderServe]):
    root: Annotated[
        AdapterRequestPlanServe | AdapterRequestRenderServe,
        Field(
            description='The one JSON request an integration reads from stdin, tagged by the\nrequested operation.'
        ),
    ]


class AdapterResultPlanServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Literal['plan_serve'] = 'plan_serve'
    output: PlanServeResult


class AdapterResult(RootModel[AdapterResultPlanServe | AdapterResultRenderServe]):
    root: Annotated[
        AdapterResultPlanServe | AdapterResultRenderServe,
        Field(
            description='The successful result of an [`AdapterRequest`], tagged by the operation it\nanswers.'
        ),
    ]


class AdapterResponseOk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: ProtocolVersion
    result: AdapterResult
    status: Literal['ok'] = 'ok'


class AdapterResponse(RootModel[AdapterResponseOk | AdapterResponseError]):
    root: Annotated[
        AdapterResponseOk | AdapterResponseError,
        Field(
            description='The one JSON response an integration writes to stdout, tagged by outcome.'
        ),
    ]


class AdapterProtocol(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bench_client_request: BenchClientRequest | None = None
    bench_client_result: BenchClientResult | None = None
    eval_client_request: EvalClientRequest | None = None
    eval_client_result: EvalClientResult | None = None
    request: AdapterRequest
    response: AdapterResponse


SettingValue.model_rebuild()
