// The documentation navigation: the Starlight sidebar, and the reading order
// of the plain-text alternates and llms.txt (ADR-0054), so both list pages in
// one order. Fixed projected pages come from the content manifest.
import { sidebarPages } from '../scripts/content-manifest.mjs';

export const sidebar = [
  { label: 'Product', link: '/' },
  { label: 'Documentation', slug: 'docs' },
  {
    label: 'Getting Started',
    items: ['docs/getting-started', ...sidebarPages('docs/getting-started')],
  },
  {
    label: 'Concepts',
    items: ['docs/concepts'],
  },
  {
    label: 'Guides',
    items: [
      'docs/guides',
      {
        label: 'Workspace authoring',
        items: [
          'docs/guides/workspace-authoring',
          ...sidebarPages('docs/guides/workspace-authoring'),
        ],
      },
      ...sidebarPages('docs/guides'),
    ],
  },
  {
    label: 'Reference',
    items: ['docs/reference', ...sidebarPages('docs/reference')],
  },
  {
    label: 'Architecture & Specification',
    items: [
      'docs/architecture',
      {
        label: 'RFCs',
        items: [
          { autogenerate: { directory: 'docs/architecture/rfc', collapsed: true } },
        ],
      },
      {
        label: 'ADRs',
        items: [
          { autogenerate: { directory: 'docs/architecture/adr', collapsed: true } },
        ],
      },
    ],
  },
];

/**
 * Order documentation page ids as the sidebar lists them. A page in an
 * autogenerated directory follows its directory's index page; a page the
 * sidebar does not name sorts after every named page.
 */
export function sidebarOrder(ids) {
  const named = [];
  const walk = (items) => {
    for (const item of items) {
      if (typeof item === 'string') named.push({ slug: item });
      else if (item.slug) named.push({ slug: item.slug });
      else if (item.autogenerate) named.push({ directory: item.autogenerate.directory });
      if (item.items) walk(item.items);
    }
  };
  walk(sidebar);
  const rank = (id) => {
    const index = named.findIndex((entry) =>
      entry.slug !== undefined
        ? entry.slug === id
        : id === entry.directory || id.startsWith(`${entry.directory}/`),
    );
    return index === -1 ? named.length : index;
  };
  return [...ids].sort((left, right) => {
    const byRank = rank(left) - rank(right);
    if (byRank !== 0) return byRank;
    return left.localeCompare(right);
  });
}
