# Rust wire source: crates/inferlab-protocol/src/wire.rs
# @generated by datamodel-codegen:
#   filename:  measurement-protocol-v1.schema.json

from enum import StrEnum
from typing import Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class BenchAgenticAcquisitionOutcome(StrEnum):
    reused = 'reused'
    downloaded = 'downloaded'


class BenchAgenticBranchStats(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    children_completed: Annotated[int, Field(ge=0)]
    children_delayed: Annotated[int, Field(ge=0)]
    children_errored: Annotated[int, Field(ge=0)]
    children_spawned: Annotated[int, Field(ge=0)]
    children_truncated: Annotated[int, Field(ge=0)]
    joins_suppressed: Annotated[int, Field(ge=0)]
    parents_failed_due_to_child_error: Annotated[int, Field(ge=0)]
    parents_resumed: Annotated[int, Field(ge=0)]
    parents_suspended: Annotated[int, Field(ge=0)]


class BenchAgenticRunEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aggregate_artifact: str
    branch_stats: BenchAgenticBranchStats
    cache_bust_records: Annotated[int, Field(ge=0)]
    context_overflow_count: Annotated[int, Field(ge=0)]
    distinct_runtime_conversations: Annotated[int, Field(ge=0)]
    distinct_source_traces: Annotated[int, Field(ge=0)]
    distinct_transport_requests: Annotated[int, Field(ge=0)]
    native_run_id: str
    ordinary_failure_count: Annotated[int, Field(ge=0)]
    profiling_began_after_warmup_and_drain: bool
    profiling_records: Annotated[int, Field(ge=0)]
    raw_records_artifact: str
    scenario: str
    source_coordinate_records: Annotated[int, Field(ge=0)]
    submission_invalid_reasons: list[str] = []
    submission_valid: bool
    unavailable_dimensions: list[str] = []
    warmup_error_records: Annotated[int, Field(ge=0)]
    warmup_records: Annotated[int, Field(ge=0)]
    warmup_source_coordinate_records: Annotated[int, Field(ge=0)]
    warmup_succeeded: bool


class BenchDatasetCacheState(StrEnum):
    missing = 'missing'
    present = 'present'


class BenchDatasetFilterInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: str
    value: str


class BenchLoadInputConcurrencyLimited(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int, Field(ge=0)]
    kind: Literal['concurrency_limited'] = 'concurrency_limited'


class BenchLoadInputRequestRateLimited(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    burstiness: float | None = None
    kind: Literal['request_rate_limited'] = 'request_rate_limited'
    request_rate: float


class BenchLoadInputUnboundedRequestRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['unbounded_request_rate'] = 'unbounded_request_rate'


class BenchLoadInput(
    RootModel[
        BenchLoadInputConcurrencyLimited
        | BenchLoadInputRequestRateLimited
        | BenchLoadInputUnboundedRequestRate
    ]
):
    root: Annotated[
        BenchLoadInputConcurrencyLimited
        | BenchLoadInputRequestRateLimited
        | BenchLoadInputUnboundedRequestRate,
        Field(description='How a Bench case paces its requests.'),
    ]


class BenchNativeInvocation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: list[str]
    exit_code: int | None = None
    interrupted: bool
    purpose: str
    timed_out: bool


class BenchPrefixSharingInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    shared_prefix_tokens: Annotated[int, Field(ge=0)]


class BenchPrefixSharingInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    shared_prefix_ratio: float


class BenchPrefixSharingInput(
    RootModel[BenchPrefixSharingInput1 | BenchPrefixSharingInput2]
):
    root: Annotated[
        BenchPrefixSharingInput1 | BenchPrefixSharingInput2,
        Field(description='One declared exact final-prompt prefix geometry.'),
    ]


class BenchPromptRouteInput(StrEnum):
    completions = 'completions'
    chat_completions = 'chat_completions'


class BenchPromptTemplateSource(StrEnum):
    request_body = 'request_body'
    prompt_table = 'prompt_table'
    tokenizer_default = 'tokenizer_default'


class BenchPromptTokenReconciliation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    native_session_num: Annotated[int, Field(ge=0)]
    observed_prompt_tokens: Annotated[int | None, Field(ge=0)] = None
    planned_prompt_tokens: Annotated[int, Field(ge=0)]
    population_index: Annotated[int, Field(ge=0)]
    reconciled: bool


class BenchRandomShapeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int, Field(ge=0)]
    weight: Annotated[int, Field(ge=0)]


class BenchRenderingAuthorityInput(StrEnum):
    local_flat = 'local_flat'
    local_template = 'local_template'
    server = 'server'


class BenchRequestRepresentationInput(StrEnum):
    flat_prompt = 'flat_prompt'
    structured_messages = 'structured_messages'


class BenchRequestSloInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minimum_good_request_ratio: float
    request_latency_ms: float | None = None
    tpot_ms: float | None = None
    ttft_ms: float | None = None


class BenchRequestSloResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    good_request_ratio: float
    good_requests: Annotated[int, Field(ge=0)]
    goodput: float
    native_aggregate_good_request_count: Annotated[int | None, Field(ge=0)] = None
    native_aggregate_good_request_count_consistent: bool | None = None
    profiling_duration_seconds: float
    profiling_duration_source: str
    request_count_reconciled: bool


class BenchRequestSourceInputRandomMixture(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['random_mixture'] = 'random_mixture'
    prefix_sharing: BenchPrefixSharingInput | None = None
    shapes: list[BenchRandomShapeInput]
    total_weight: Annotated[int, Field(ge=0)]


class BenchSessionDatasetCatalogInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache_path: str
    cache_state: BenchDatasetCacheState
    configuration: str | None = None
    dataset: str
    filter: BenchDatasetFilterInput | None = None
    license: str
    materialization_identity: str
    profile: str | None = None
    provides_output_targets: bool
    sha256: str
    source: str
    source_format: str
    split: str | None = None
    upstream_identity: str
    url: str


class BenchSessionPhaseSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempted_requests: Annotated[int, Field(ge=0)]
    completed_requests: Annotated[int, Field(ge=0)]
    failed_requests: Annotated[int, Field(ge=0)]
    failed_sessions: Annotated[int, Field(ge=0)]
    planned_requests: Annotated[int, Field(ge=0)]
    planned_sessions: Annotated[int, Field(ge=0)]
    reconciled: bool
    started_sessions: Annotated[int, Field(ge=0)]
    succeeded_sessions: Annotated[int, Field(ge=0)]


class BenchSessionSourceInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalog: BenchSessionDatasetCatalogInput
    dataset: str
    inter_turn_delay_scale: float
    max_input_tokens: Annotated[int, Field(ge=0)]
    max_inter_turn_delay_seconds: float | None = None
    output_tokens: Annotated[int | None, Field(ge=0)] = None
    profile: str | None = None


class BenchSessionTemplateInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    template_identity: str
    turn_count: Annotated[int, Field(ge=0)]


class BenchSessionTurnResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    effective_inter_turn_delay_seconds: float | None = None
    inter_turn_delay_reconciled: bool | None = None
    native_artifact_name: str
    native_session_num: Annotated[int, Field(ge=0)]
    observed_prompt_tokens: Annotated[int | None, Field(ge=0)] = None
    phase: str
    post_failure_continuation: bool = False
    pre_template_content_tokens: Annotated[int, Field(ge=0)]
    preceding_native_session_num: Annotated[int | None, Field(ge=0)] = None
    preceding_terminal_response_receipt_ns: Annotated[int | None, Field(ge=0)] = None
    request_start_ns: Annotated[int, Field(ge=0)]
    runtime_session_id: str
    turn_index: Annotated[int, Field(ge=0)]


class BenchSharedSystemContentInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tokens: Annotated[int, Field(ge=0)]


class BenchSharedSystemContentInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ratio: float


class BenchSharedSystemContentInput(
    RootModel[BenchSharedSystemContentInput1 | BenchSharedSystemContentInput2]
):
    root: Annotated[
        BenchSharedSystemContentInput1 | BenchSharedSystemContentInput2,
        Field(
            description='One pre-template shared system-content declaration for server-rendered\nsynthetic chat.'
        ),
    ]


class BenchTokenCountSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maximum: Annotated[int, Field(ge=0)]
    mean: float
    minimum: Annotated[int, Field(ge=0)]


class BenchTokenDistributionKindInput(RootModel[Literal['inclusive_uniform']]):
    root: Literal['inclusive_uniform'] = 'inclusive_uniform'


class BenchTokenSelectorInput1(RootModel[int]):
    root: Annotated[
        int,
        Field(
            description='One fixed or bounded inclusive-uniform token-length selector.',
            ge=0,
        ),
    ]


class ClientStatus(StrEnum):
    succeeded = 'succeeded'
    failed = 'failed'


class EndpointProtocol(RootModel[Literal['http']]):
    root: Annotated[
        Literal['http'],
        Field(description='The application protocol a workload endpoint speaks.'),
    ] = 'http'


class EvalDefinitionInputOpenaiSmoke(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['openai_smoke'] = 'openai_smoke'
    max_tokens: Annotated[int, Field(ge=0)]
    prompt: str
    timeout_seconds: Annotated[int, Field(ge=0)]


class EvalFailureKind(StrEnum):
    task_resolution = 'task_resolution'
    probe_tokenizer = 'probe_tokenizer'
    probe_transport = 'probe_transport'
    probe_http = 'probe_http'
    probe_malformed_response = 'probe_malformed_response'
    probe_generated_only_logprobs = 'probe_generated_only_logprobs'
    probe_tokenizer_alignment = 'probe_tokenizer_alignment'
    metric_normalization = 'metric_normalization'


class EvalMetricComparison(StrEnum):
    at_least = 'at_least'
    at_most = 'at_most'


class EvalMetricGateConclusion(StrEnum):
    passed = 'passed'
    failed = 'failed'


class EvalNormalizedMetric(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: str | None = None
    higher_is_better: bool
    metric: str
    native_metric_key: str
    source_identity: str
    value: float


class EvalTaskSourceInputBuiltIn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['built_in'] = 'built_in'
    name: str


class EvalTaskSourceInputBundled(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_asset_sha256: str
    kind: Literal['bundled'] = 'bundled'
    name: str
    path: str
    prompt_asset_sha256: str
    scorer_sha256: str
    task_closure_sha256: str
    task_definition_sha256: str
    task_identity: str


class EvalTaskSourceInputWorkspaceYaml(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['workspace_yaml'] = 'workspace_yaml'
    path: str


class EvalTaskSourceInput(
    RootModel[
        EvalTaskSourceInputBuiltIn
        | EvalTaskSourceInputBundled
        | EvalTaskSourceInputWorkspaceYaml
    ]
):
    root: Annotated[
        EvalTaskSourceInputBuiltIn
        | EvalTaskSourceInputBundled
        | EvalTaskSourceInputWorkspaceYaml,
        Field(
            description='The resolved lm-eval task source consumed by the release-owned Eval runner.'
        ),
    ]


class EvalTrialSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed_trials: Annotated[int, Field(ge=0)]
    higher_is_better: bool
    issued_trials: Annotated[int, Field(ge=0)]
    pass_rate: float | None = None
    passed_trials: Annotated[int, Field(ge=0)]
    per_trial_filter: str | None = None
    per_trial_metric: str
    request_failure_trials: Annotated[int, Field(ge=0)]
    requested_trials: Annotated[int, Field(ge=0)]
    unissued_trials: Annotated[int, Field(ge=0)]


class MeasurementModelInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locator: str
    served_name: str


class ProtocolVersion(RootModel[Literal['7']]):
    root: Annotated[
        Literal['7'],
        Field(
            description='The shared protocol version used by framework integrations and release-owned\nmeasurement clients. The only accepted value is `7` (serialized as the\nstring `"7"`); a mismatch is rejected before lowering.'
        ),
    ] = '7'


class RawArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: str
    name: str
    path: str


class ServerMetricsEndpointInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    port_name: str | None = None
    url: str


class SettingValue(
    RootModel[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]]
    ]
):
    root: Annotated[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]],
        Field(
            description='A framework-specific server setting value carried as structured JSON data\n(never a pre-rendered shell fragment) across the integration boundary.'
        ),
    ]


class BenchAgenticCatalogInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aiperf_loader: str
    aiperf_revision: str
    aiperf_version: str
    approximate_bytes: Annotated[int, Field(ge=0)]
    cache_bust: str
    cache_path: str
    cache_state: BenchDatasetCacheState
    cache_warmup_seconds: Annotated[int, Field(ge=0)]
    concurrency_semantics: str
    dataset_configuration_timeout_seconds: Annotated[int, Field(ge=0)]
    dataset_entries: Annotated[int, Field(ge=0)]
    default_duration_seconds: Annotated[int, Field(ge=0)]
    failure_threshold: float
    filename: str
    global_idle_gap_cap_seconds: float
    gpu_telemetry: bool
    ignore_eos: bool
    inferencex_reference: str
    inferencex_repository: str
    inferencex_revision: str
    license: str
    materialization_identity: str
    minimum_duration_seconds: Annotated[int, Field(ge=0)]
    replay_semantics: str
    repository: str
    required_artifacts: list[str]
    revision: str
    scenario: str
    server_metric_slice_seconds: Annotated[int, Field(ge=0)]
    service_profile_configuration_timeout_seconds: Annotated[int, Field(ge=0)]
    sha256: str
    source_format: str
    streaming: bool
    trace_count: Annotated[int, Field(ge=0)]
    trajectory_start_max: float
    trajectory_start_min: float
    unavailable_dimensions: list[str]
    use_server_token_count: bool
    warmup_grace_seconds: Annotated[int, Field(ge=0)]


class BenchAgenticSourceInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalog: BenchAgenticCatalogInput
    dataset: str
    profile: str


class BenchAgenticSourceVerification(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acquisition_outcome: BenchAgenticAcquisitionOutcome | None = None
    cache_path: str | None = None
    cache_state_before: BenchDatasetCacheState
    expected_revision: str
    expected_sha256: str
    filename: str
    observed_revision: str | None = None
    observed_sha256: str | None = None
    repository: str


class BenchCaseInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    duration_seconds: Annotated[int | None, Field(ge=0)] = None
    load_shape: BenchLoadInput
    request_count: Annotated[int, Field(ge=0)]
    session_count: Annotated[int | None, Field(ge=0)] = None
    warmup_request_count: Annotated[int, Field(ge=0)] = 0
    warmup_session_count: Annotated[int | None, Field(ge=0)] = None


class BenchDatasetCatalogInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    aiperf_format: str
    cache_path: str
    cache_state: BenchDatasetCacheState
    configuration: str | None = None
    dataset: str
    filter: BenchDatasetFilterInput | None = None
    license: str
    materialization_identity: str
    profile: str | None = None
    provides_output_targets: bool
    sha256: str
    source: str
    source_format: str
    split: str | None = None
    upstream_identity: str
    url: str


class BenchInclusiveUniformInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: BenchTokenDistributionKindInput
    max: Annotated[int, Field(ge=0)]
    min: Annotated[int, Field(ge=0)]


class BenchPopulationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: Annotated[int, Field(ge=0)]
    evidence_path: str
    path: str
    session_templates: Annotated[
        list[BenchSessionTemplateInput], Field(validate_default=True)
    ] = []
    sha256: str
    tpot_applicable: bool


class BenchPrefixGeometrySummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    canonical_prefix_sha256: str
    full_prompt_entries: Annotated[int, Field(ge=0)]
    maximum_shared_prefix_tokens: Annotated[int, Field(ge=0)]
    shared_prefix_tokens: BenchTokenCountSummary
    unique_suffix_tokens: BenchTokenCountSummary


class BenchPromptInputFlat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['flat'] = 'flat'
    rendering_authority: BenchRenderingAuthorityInput
    request_representation: BenchRequestRepresentationInput
    route: BenchPromptRouteInput


class BenchPromptInputRenderedChat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_template: str | None = None
    chat_template_kwargs: Annotated[
        dict[str, SettingValue], Field(validate_default=True)
    ] = {}
    kind: Literal['rendered_chat'] = 'rendered_chat'
    rendering_authority: BenchRenderingAuthorityInput
    request_representation: BenchRequestRepresentationInput
    route: BenchPromptRouteInput


class BenchPromptInputServerChat(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['server_chat'] = 'server_chat'
    rendering_authority: BenchRenderingAuthorityInput
    request_representation: BenchRequestRepresentationInput
    route: BenchPromptRouteInput


class BenchPromptInput(
    RootModel[
        BenchPromptInputFlat | BenchPromptInputRenderedChat | BenchPromptInputServerChat
    ]
):
    root: Annotated[
        BenchPromptInputFlat
        | BenchPromptInputRenderedChat
        | BenchPromptInputServerChat,
        Field(
            description='The frozen prompt representation, route, and rendering authority for a\nserving Bench population.'
        ),
    ]


class BenchPromptTemplateProjection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    content: str
    sha256: str
    source: BenchPromptTemplateSource


class BenchPromptTokenTargetingSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    exact_entries: Annotated[int, Field(ge=0)]
    fallback_entries: Annotated[int, Field(ge=0)]
    fallback_reasons: dict[str, int] = {}
    pre_template_content_tokens: BenchTokenCountSummary
    projection_template: BenchPromptTemplateProjection | None = None
    selected_prompt_tokens: BenchTokenCountSummary


class BenchRequestSourceInputDataset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalog: BenchDatasetCatalogInput
    dataset: str
    kind: Literal['dataset'] = 'dataset'
    max_input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int | None, Field(ge=0)] = None
    profile: str | None = None


class BenchRuntimeSessionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempted_turns: Annotated[int, Field(ge=0)]
    diagnostic: str | None = None
    failing_turn: Annotated[int | None, Field(ge=0)] = None
    failure_classification: str | None = None
    phase: str
    planned_turns: Annotated[int, Field(ge=0)]
    runtime_session_id: str
    status: ClientStatus
    suppressed_later_turns: Annotated[int, Field(ge=0)]
    template_identity: str


class BenchSessionResultEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    counts_reconciled: bool
    inter_turn_delays_reconciled: bool
    native_requests_reconciled: bool
    population_slice_reconciled: bool
    profiling: BenchSessionPhaseSummary
    sessions: list[BenchRuntimeSessionResult]
    sessions_reconciled: bool
    turn_order_reconciled: bool
    turns: list[BenchSessionTurnResult]
    warmup: BenchSessionPhaseSummary


class BenchSharedSystemContentSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    canonical_system_content_sha256: str
    system_content_tokens: BenchTokenCountSummary
    user_content_tokens: BenchTokenCountSummary


class BenchTokenSelectorInput(
    RootModel[BenchTokenSelectorInput1 | BenchInclusiveUniformInput]
):
    root: Annotated[
        BenchTokenSelectorInput1 | BenchInclusiveUniformInput,
        Field(
            description='One fixed or bounded inclusive-uniform token-length selector.'
        ),
    ]


class ClientEndpointInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_completions_path: str
    completions_path: str
    host: str
    port: Annotated[int, Field(ge=0, le=65535)]
    protocol: EndpointProtocol
    server_metrics: ServerMetricsEndpointInput | None = None


class EvalDefinitionInputLmEval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int | None, Field(ge=0)] = None
    few_shot: Annotated[int | None, Field(ge=0)] = None
    kind: Literal['lm_eval'] = 'lm_eval'
    limit: Annotated[int | None, Field(ge=0)] = None
    max_tokens: Annotated[int | None, Field(ge=0)] = None
    metric: str
    metric_filter: str | None = None
    request_body: Annotated[dict[str, SettingValue], Field(validate_default=True)] = {}
    seed: Annotated[int | None, Field(ge=0)] = None
    task: EvalTaskSourceInput
    threshold: float
    timeout_seconds: Annotated[int, Field(ge=0)]
    trials: Annotated[int, Field(ge=0)]


class EvalDefinitionInput(
    RootModel[EvalDefinitionInputOpenaiSmoke | EvalDefinitionInputLmEval]
):
    root: Annotated[
        EvalDefinitionInputOpenaiSmoke | EvalDefinitionInputLmEval,
        Field(
            description='The measurement an Eval client runs against the workload endpoint.'
        ),
    ]


class EvalMetricGate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comparison: EvalMetricComparison
    conclusion: EvalMetricGateConclusion
    metric: EvalNormalizedMetric
    threshold: float


class BenchAgenticResultEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run: BenchAgenticRunEvidence | None = None
    source: BenchAgenticSourceVerification


class BenchClientResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentic_evidence: BenchAgenticResultEvidence | None = None
    completed_requests: Annotated[int, Field(ge=0)]
    error: str | None = None
    failed_requests: Annotated[int, Field(ge=0)]
    metrics: dict[str, float]
    native_command: list[str]
    native_exit_code: int | None = None
    normalization_schema: str
    prompt_token_reconciliation: Annotated[
        list[BenchPromptTokenReconciliation], Field(validate_default=True)
    ] = []
    raw_artifacts: list[RawArtifact]
    report_invocations: Annotated[
        list[BenchNativeInvocation], Field(validate_default=True)
    ] = []
    request_slo: BenchRequestSloResult | None = None
    schema_version: Annotated[
        int,
        Field(
            description='Result envelope version; clients write `1`. The measurement runtime\nrejects a bench result whose version is not `1`.',
            ge=0,
        ),
    ]
    session_evidence: BenchSessionResultEvidence | None = None
    status: ClientStatus


class BenchPopulationPreparationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admitted_entries: Annotated[int, Field(ge=0)]
    candidate_entries: Annotated[int, Field(ge=0)]
    error: str | None = None
    evidence_path: str | None = None
    ineligible_entries: Annotated[int, Field(ge=0)]
    ineligible_reasons: dict[str, int] = {}
    input_tokens: BenchTokenCountSummary | None = None
    materialization_identity: str
    output_tokens: BenchTokenCountSummary | None = None
    population: BenchPopulationInput | None = None
    prefix_geometry: BenchPrefixGeometrySummary | None = None
    prompt_token_targeting: BenchPromptTokenTargetingSummary | None = None
    requested_entries: Annotated[int, Field(ge=0)]
    schema_version: Annotated[int, Field(ge=0)]
    shared_system_content: BenchSharedSystemContentSummary | None = None
    status: ClientStatus


class BenchRequestSourceInputRandom(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_tokens: BenchTokenSelectorInput
    kind: Literal['random'] = 'random'
    output_tokens: BenchTokenSelectorInput
    prefix_sharing: BenchPrefixSharingInput | None = None
    shared_system_content: BenchSharedSystemContentInput | None = None


class BenchRequestSourceInput(
    RootModel[
        BenchRequestSourceInputRandom
        | BenchRequestSourceInputRandomMixture
        | BenchRequestSourceInputDataset
    ]
):
    root: Annotated[
        BenchRequestSourceInputRandom
        | BenchRequestSourceInputRandomMixture
        | BenchRequestSourceInputDataset,
        Field(
            description='One closed request origin lowered by Inferlab for the Bench runtime.'
        ),
    ]


class EvalClientRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    case_budget_seconds: Annotated[
        float,
        Field(
            description='Remaining control-plane case budget when the client is released.'
        ),
    ]
    definition: EvalDefinitionInput
    endpoint: ClientEndpointInput
    model: MeasurementModelInput
    protocol_version: ProtocolVersion
    workspace_root: str
    workspace_source_exclusions: list[str]


class EvalClientResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str | None = None
    failure_kind: EvalFailureKind | None = None
    gate: EvalMetricGate | None = None
    metrics: dict[str, float]
    native_command: list[str]
    native_exit_code: int | None = None
    native_timed_out: bool = False
    normalized_metrics: Annotated[
        dict[str, EvalNormalizedMetric], Field(validate_default=True)
    ] = {}
    raw_artifacts: list[RawArtifact]
    schema_version: Annotated[
        int,
        Field(
            description='Result envelope version; clients write `1`. The measurement runtime\nrejects an eval result whose version is not `1`.',
            ge=0,
        ),
    ]
    status: ClientStatus
    trial_summary: EvalTrialSummary | None = None


class BenchDefinitionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    agentic_source: BenchAgenticSourceInput | None = None
    prompt: BenchPromptInput
    request_body: Annotated[dict[str, SettingValue], Field(validate_default=True)] = {}
    request_slo: BenchRequestSloInput | None = None
    request_source: BenchRequestSourceInput | None = None
    reset_prefix_cache: bool = False
    seed: Annotated[int, Field(ge=0)]
    server_metrics: bool = False
    session_source: BenchSessionSourceInput | None = None
    timeout_seconds: Annotated[int, Field(ge=0)]


class BenchPopulationPreparationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    model: MeasurementModelInput
    prompt: BenchPromptInput
    protocol_version: ProtocolVersion
    request_body: Annotated[dict[str, SettingValue], Field(validate_default=True)] = {}
    request_source: BenchRequestSourceInput | None = None
    required_entries: Annotated[int, Field(ge=0)]
    seed: Annotated[int, Field(ge=0)]
    session_source: BenchSessionSourceInput | None = None
    source_path: str | None = None
    tokenizer_backend: str
    transformers_version: str


class BenchClientRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    case: BenchCaseInput
    case_budget_seconds: Annotated[
        float,
        Field(
            description='Remaining control-plane case budget when the client is released.'
        ),
    ]
    definition: BenchDefinitionInput
    endpoint: ClientEndpointInput
    model: MeasurementModelInput
    population: BenchPopulationInput | None = None
    protocol_version: ProtocolVersion


class MeasurementProtocol(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bench_client_request: BenchClientRequest | None = None
    bench_client_result: BenchClientResult | None = None
    bench_population_preparation_request: BenchPopulationPreparationRequest | None = (
        None
    )
    bench_population_preparation_result: BenchPopulationPreparationResult | None = None
    eval_client_request: EvalClientRequest | None = None
    eval_client_result: EvalClientResult | None = None


SettingValue.model_rebuild()
