//! Generated runtime-only image build contexts ([[RFC-0007:C-IMAGE-BUILD]]).
//!
//! Inferlab derives the context from resolved workspace facts: the committed
//! Pixi lock environment (rendered as a hash-pinned explicit spec), framework
//! wheels built locally from the stack sources (copied by bytes,
//! installed with pinned hashes), and the digest-resolved base image. The
//! workspace never authors container build files, and machine-private facts
//! are rejected before assembly by the portable-output guard.

use crate::InferlabError;
use crate::workspace::LoadedWorkspace;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

pub const GENERATOR_IDENTITY: &str = concat!("inferlab-image-context/", env!("CARGO_PKG_VERSION"));

/// Package build-procedure identity ([[RFC-0007:C-IMAGE-BUILD]]): bump when
/// the wheel build procedure changes behavior (copy sanitization, build
/// flags, cache layout or key derivation, publication protocol) without a
/// crate version change. Enters both the wheel cache key and the image
/// content closure, so a procedure change invalidates cached wheels and
/// changes the closure digest together.
pub const WHEEL_BUILD_EPOCH: u32 = 5;

/// Context-generation procedure identity ([[RFC-0007:C-IMAGE-BUILD]]): bump
/// when Dockerfile rendering, package projection, or context layout changes
/// without a crate version change. Enters the image content closure only —
/// context layout does not affect wheel bytes.
/// Epoch 2: environment postprocess and check RUN layers execute through the
/// entrypoint inside assembly ([[RFC-0002:C-ENVIRONMENT-CHECKS]]).
/// Epoch 3: checks execute through a generated runner that frames per-check
/// results into the builder log, so a failed build still attributes which
/// checks ran and how they exited.
pub const IMAGE_CONTEXT_EPOCH: u32 = 3;

/// The framing prefix the generated check runner emits per check; the
/// builder log is scanned for it to reconstruct per-check evidence.
pub const CHECK_MARKER: &str = "INFERLAB-CHECK";

const ENTRYPOINT_PATH: &str = "/usr/local/bin/inferlab-entrypoint";
const ENV_PREFIX: &str = "/opt/inferlab-env";
const CHECKS_CONTEXT_DIR: &str = "environment-checks";
const POSTPROCESS_CONTEXT_DIR: &str = "environment-postprocess";
const CHECKS_IMAGE_DIR: &str = "/opt/inferlab-checks";
const POSTPROCESS_IMAGE_DIR: &str = "/opt/inferlab-postprocess";
const CHECKS_RUNNER_FILE: &str = "inferlab-environment-checks.sh";
const CHECKS_RUNNER_IMAGE_PATH: &str = "/opt/inferlab-environment-checks.sh";

/// The generated in-image check runner ([[RFC-0002:C-ENVIRONMENT-CHECKS]]):
/// every declared check executes, each frames its exit into the builder log,
/// and the layer fails when any check failed — so a failed build still says
/// which checks ran and how they exited, while an image can only exist with
/// every check green.
fn render_checks_runner(checks: &[ContextScript]) -> String {
    let mut lines = vec![
        format!("#!/bin/sh\n# Generated by {GENERATOR_IDENTITY}; do not edit."),
        "failed=0".to_owned(),
    ];
    for script in checks {
        lines.push(format!("python {CHECKS_IMAGE_DIR}/{}.py", script.id));
        lines.push("status=$?".to_owned());
        lines.push(format!(
            "printf '{CHECK_MARKER} %s exit=%s\\n' '{}' \"$status\"",
            script.id
        ));
        lines.push("if [ \"$status\" -ne 0 ]; then failed=1; fi".to_owned());
    }
    lines.push("exit \"$failed\"".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

/// The entrypoint/command contract contribution to the content closure. The
/// contract is hashed over the rendered script so activation projections are
/// behavior-affecting closure inputs, while the closure map itself carries no
/// in-image program paths.
pub fn entrypoint_contract_digest(rendered_entrypoint: &str) -> String {
    format!(
        "{:x}",
        Sha256::digest(format!("{ENTRYPOINT_PATH}\u{1e}{rendered_entrypoint}").as_bytes())
    )
}

/// The selected environment's feature composition: the named features in
/// declaration order, and whether the default feature (the workspace-level
/// tables) applies. An environment absent from `[environments]` (for example
/// the implicit `default`) composes no named features.
fn composed_features(data: &toml::Value, environment: &str) -> (Vec<String>, bool) {
    match data
        .get("environments")
        .and_then(|environments| environments.get(environment))
    {
        Some(toml::Value::Array(features)) => (
            features
                .iter()
                .filter_map(toml::Value::as_str)
                .map(str::to_owned)
                .collect(),
            true,
        ),
        Some(toml::Value::Table(table)) => (
            table
                .get("features")
                .and_then(toml::Value::as_array)
                .map(|features| {
                    features
                        .iter()
                        .filter_map(toml::Value::as_str)
                        .map(str::to_owned)
                        .collect()
                })
                .unwrap_or_default(),
            !table
                .get("no-default-feature")
                .and_then(toml::Value::as_bool)
                .unwrap_or(false),
        ),
        _ => (Vec::new(), true),
    }
}

/// Whether a feature-shaped table (the workspace root or one `[feature.*]`
/// entry) declares activation scripts, directly or under a target.
fn declares_activation_scripts(node: &toml::Value, pixi_platform: &str) -> bool {
    let direct = node
        .get("activation")
        .and_then(|activation| activation.get("scripts"))
        .is_some();
    let targeted = node
        .get("target")
        .and_then(|target| target.get(pixi_platform))
        .and_then(|target| target.get("activation"))
        .and_then(|activation| activation.get("scripts"))
        .is_some();
    direct || targeted
}

/// Reject activation scripts that bind to the selected environment
/// ([[RFC-0007:C-IMAGE-BUILD]]): a script's exports are not statically
/// knowable, so the cache key, sanitized-view redirects, and entrypoint
/// projection would all silently miss them. Feature-scoped `activation.env`
/// is composed by the projection and is legal; scripts under features the
/// environment does not compose are inert and stay legal too.
pub fn guard_unmodeled_activation(
    root: &Path,
    pixi_platform: &str,
    environment: &str,
) -> Result<(), InferlabError> {
    let manifest = root.join("pixi.toml");
    let text = fs::read_to_string(&manifest).map_err(|source| InferlabError::Read {
        path: manifest.clone(),
        source,
    })?;
    let data: toml::Value = toml::from_str(&text).map_err(|source| InferlabError::ParseToml {
        path: manifest,
        source,
    })?;
    let (features, include_default) = composed_features(&data, environment);
    if include_default && declares_activation_scripts(&data, pixi_platform) {
        return Err(InferlabError::ImageBuild {
            message: "pixi.toml declares [activation] scripts, which image production cannot \
                      project; move the exports into [activation.env]"
                .to_owned(),
        });
    }
    for name in &features {
        let declares = data
            .get("feature")
            .and_then(|table| table.get(name))
            .is_some_and(|feature| declares_activation_scripts(feature, pixi_platform));
        if declares {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "environment {environment:?} composes feature {name:?}, which declares \
                     activation scripts that image production cannot project; move the \
                     exports into the feature's [activation.env]"
                ),
            });
        }
    }
    Ok(())
}

/// Read the committed Pixi manifest's activation env for one environment and
/// platform — the workspace's single authority for serving activation facts,
/// projected into the image instead of a framework-specific template.
///
/// Feature composition follows Pixi's observed precedence (verified against
/// pixi 0.71.2 and pinned by the manual differential test): earlier-listed
/// features win over later ones, a feature's target table overrides its
/// untargeted table, and the default feature (the workspace-level tables)
/// applies last unless the environment sets `no-default-feature`. The merge
/// inserts in reverse precedence so later inserts overwrite.
pub fn activation_env(
    root: &Path,
    pixi_platform: &str,
    environment: &str,
) -> Result<BTreeMap<String, String>, InferlabError> {
    let manifest = root.join("pixi.toml");
    let text = fs::read_to_string(&manifest).map_err(|source| InferlabError::Read {
        path: manifest.clone(),
        source,
    })?;
    let data: toml::Value = toml::from_str(&text).map_err(|source| InferlabError::ParseToml {
        path: manifest,
        source,
    })?;
    let (features, include_default) = composed_features(&data, environment);
    let mut env = BTreeMap::new();
    let mut merge = |node: &toml::Value| {
        let tables = [
            node.get("activation"),
            node.get("target")
                .and_then(|target| target.get(pixi_platform))
                .and_then(|target| target.get("activation")),
        ];
        for activation in tables.into_iter().flatten() {
            if let Some(entries) = activation.get("env").and_then(toml::Value::as_table) {
                for (name, value) in entries {
                    if let Some(value) = value.as_str() {
                        env.insert(name.clone(), value.to_owned());
                    }
                }
            }
        }
    };
    if include_default {
        merge(&data);
    }
    for name in features.iter().rev() {
        if let Some(feature) = data.get("feature").and_then(|table| table.get(name)) {
            merge(feature);
        }
    }
    Ok(env)
}

/// The rendered activation entrypoint. Projection rules, combining the v0 and
/// v1 precedents ([[ADR-0005]]):
/// - `$CONDA_PREFIX` references stay unexpanded and resolve to the baked
///   prefix exported first.
/// - Values referencing `$PIXI_PROJECT_ROOT` are workspace-tree facts with no
///   in-image equivalent; they are skipped and reported (DeepGEMM sources are
///   compiled into the vLLM wheel at build time, not consumed at runtime).
/// - Credential-named variables are skipped and reported; credentials never
///   enter portable artifacts.
/// - Self-referencing values (`CPATH=...:$CPATH`) export plainly so injected
///   values compose; all others use `${VAR:-...}` so `docker run --env` wins.
pub struct RenderedEntrypoint {
    pub text: String,
    pub skipped: Vec<String>,
}

pub fn render_entrypoint(
    activation: &BTreeMap<String, String>,
) -> Result<RenderedEntrypoint, InferlabError> {
    let mut lines = vec![
        "#!/bin/sh".to_owned(),
        "set -eu".to_owned(),
        format!("export CONDA_PREFIX=\"{ENV_PREFIX}\""),
        format!("export PATH=\"{ENV_PREFIX}/bin:${{PATH:-}}\""),
    ];
    let mut skipped = Vec::new();
    for (name, value) in activation {
        if crate::workspace::MANAGED_CONTAINER_ENV.contains(&name.as_str()) {
            // Inferlab-managed container variables never project from
            // activation: CONDA_PREFIX is owned by the baked prefix,
            // CUDA_VISIBLE_DEVICES is a runtime placement fact, and
            // HOME/USER/LOGNAME are injected at validation launch.
            skipped.push(name.clone());
            continue;
        }
        if credential_name(name) {
            // Credential material must never enter portable artifacts;
            // runtime credentials reach validation containers through the
            // per-machine `container.pass_env` binding (`--env NAME`), which
            // the `${VAR:-...}` export form honors.
            skipped.push(name.clone());
            continue;
        }
        if value.contains("$PIXI_PROJECT_ROOT") || value.contains("${PIXI_PROJECT_ROOT") {
            skipped.push(name.clone());
            continue;
        }
        if value.contains('"')
            || value.contains('`')
            || value.contains('\\')
            || value.contains("$(")
        {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "activation value {name:?} contains shell-active characters and cannot be \
                     projected into the image entrypoint"
                ),
            });
        }
        let self_reference =
            value.contains(&format!("${name}")) || value.contains(&format!("${{{name}}}"));
        if self_reference {
            // Rewrite the self-reference to default-empty form so the export
            // composes under `set -u` in a fresh container.
            let guarded = guard_self_reference(value, name);
            lines.push(format!("export {name}=\"{guarded}\""));
        } else {
            lines.push(format!("export {name}=\"${{{name}:-{value}}}\""));
        }
    }
    lines.push("exec \"$@\"".to_owned());
    lines.push(String::new());
    Ok(RenderedEntrypoint {
        text: lines.join("\n"),
        skipped,
    })
}

pub struct ContextInputs<'a> {
    pub context_dir: &'a Path,
    pub base_image: &'a str,
    pub base_image_digest: &'a str,
    /// The rendered activation entrypoint script.
    pub entrypoint: &'a str,
    /// Wheels built from the stack sources, copied by bytes.
    pub built_wheels: &'a [BuiltWheel],
    /// Declared environment checks, copied by bytes and executed as RUN
    /// layers through the entrypoint ([[RFC-0002:C-ENVIRONMENT-CHECKS]]).
    pub checks: &'a [ContextScript],
    /// Declared image-realization postprocess steps, executed before the
    /// checks.
    pub postprocess: &'a [ContextScript],
}

/// A committed workspace script copied into the frozen context. Committed
/// content stays under the workspace author's secret posture, not the
/// generated-text portability guard.
#[derive(Clone, Debug)]
pub struct ContextScript {
    pub id: String,
    pub bytes: Vec<u8>,
}

#[derive(Clone, Debug)]
pub struct BuiltWheel {
    pub package: String,
    pub filename: String,
    pub source_path: PathBuf,
    pub sha256: String,
}

#[derive(Clone, Debug)]
pub struct PreparedContext {
    pub context_dir: PathBuf,
    pub dockerfile: String,
    /// Every rendered text destined for the image: checked by the
    /// portable-output guard before assembly.
    pub rendered: Vec<(String, String)>,
}

/// Map an OCI platform (`linux/amd64`) to the Pixi platform (`linux-64`).
pub fn pixi_platform(oci_platform: &str) -> Result<&'static str, InferlabError> {
    match oci_platform {
        "linux/amd64" => Ok("linux-64"),
        "linux/arm64" => Ok("linux-aarch64"),
        other => Err(InferlabError::ImageBuild {
            message: format!("unsupported target platform {other:?}"),
        }),
    }
}

#[derive(Debug, Deserialize)]
struct PixiListEntry {
    name: String,
    kind: String,
    #[serde(default)]
    url: Option<String>,
    #[serde(default)]
    sha256: Option<String>,
}

/// List the locked packages of one environment via `pixi list --json`; Pixi
/// remains the only package authority. The listing covers the host platform,
/// which is the only platform the local builder assembles. Entries without a
/// registry hash are source-backed (editable path dependencies) and are
/// either replaced by locally built wheels or deliberately excluded.
pub fn locked_packages(root: &Path, environment: &str) -> Result<Vec<PackageSpec>, InferlabError> {
    let output = Command::new("pixi")
        .current_dir(root)
        .args(["list", "--json", "--environment", environment])
        .output()
        .map_err(|source| InferlabError::LaunchPixi {
            action: "list",
            source,
        })?;
    if !output.status.success() {
        return Err(InferlabError::ImageBuild {
            message: format!(
                "pixi list failed for environment {environment:?}: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ),
        });
    }
    let entries: Vec<PixiListEntry> =
        serde_json::from_slice(&output.stdout).map_err(|error| InferlabError::ImageBuild {
            message: format!("pixi list produced invalid JSON: {error}"),
        })?;
    if entries.is_empty() {
        return Err(InferlabError::ImageBuild {
            message: format!("pixi list reported no packages for environment {environment:?}"),
        });
    }
    Ok(entries
        .into_iter()
        .map(|entry| {
            let editable = entry.sha256.is_none() && entry.kind != "conda";
            PackageSpec {
                name: entry.name,
                kind: match entry.kind.as_str() {
                    "conda" => PackageKind::Conda,
                    _ => PackageKind::Pypi,
                },
                url: entry.url,
                sha256: entry.sha256,
                editable,
            }
        })
        .collect())
}

/// Content identity of the selected environment's locked package closure
/// ([[RFC-0007:C-IMAGE-BUILD]]): only pinned upstream packages move this
/// digest — editable entries are excluded because their identity is the
/// committed source state, which the cache key already carries exactly.
/// Unlike whole-file manifest digests, unrelated environments, platforms,
/// tasks, and format churn leave this stable.
pub fn locked_closure_digest(packages: &[PackageSpec]) -> String {
    let canonical: Vec<String> = packages
        .iter()
        .filter(|package| !package.editable)
        .map(|package| {
            format!(
                "{}\u{1f}{:?}\u{1f}{}\u{1f}{}",
                package.name,
                package.kind,
                package.url.as_deref().unwrap_or(""),
                package.sha256.as_deref().unwrap_or("")
            )
        })
        .collect();
    format!("{:x}", Sha256::digest(canonical.join("\u{1e}").as_bytes()))
}

/// Content identities for editable packages installed outside the stack sources
/// ([[RFC-0007:C-IMAGE-BUILD]]): stack-source editables are covered exactly by
/// committed git identities, but external path dependencies (for example
/// Inferlab's own adapter and integration packages from a sibling repository)
/// sit in the build environment with no other identity, so their tree content
/// enters the cache key. Paths come from `pixi list` itself — the package
/// authority — not from a second manifest parse.
pub fn editable_identities(
    root: &Path,
    packages: &[PackageSpec],
    source_paths: &[PathBuf],
) -> Result<Vec<String>, InferlabError> {
    let mut identities = Vec::new();
    for package in packages {
        if !package.editable {
            continue;
        }
        let Some(url) = &package.url else {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "editable package {:?} reports no source path; its build-input identity \
                     cannot be derived",
                    package.name
                ),
            });
        };
        let relative = Path::new(url.strip_prefix("./").unwrap_or(url));
        if source_paths.iter().any(|path| relative.starts_with(path)) {
            continue;
        }
        let digest = tree_digest(&root.join(relative))?;
        identities.push(format!("{}\u{1f}{digest}", relative.display()));
    }
    identities.sort();
    Ok(identities)
}

/// Deterministic content digest of one source tree: files sorted by relative
/// path, hashing path and bytes. Derived artifacts that churn without a
/// source change (`.git`, `__pycache__`, `*.egg-info`) are excluded; symlinks
/// contribute their target string.
fn tree_digest(path: &Path) -> Result<String, InferlabError> {
    fn walk(dir: &Path, files: &mut Vec<PathBuf>) -> Result<(), InferlabError> {
        let entries = fs::read_dir(dir).map_err(|source| InferlabError::Read {
            path: dir.to_path_buf(),
            source,
        })?;
        for entry in entries {
            let entry = entry.map_err(|source| InferlabError::Read {
                path: dir.to_path_buf(),
                source,
            })?;
            let name = entry.file_name().to_string_lossy().into_owned();
            if name == ".git" || name == "__pycache__" || name.ends_with(".egg-info") {
                continue;
            }
            let file_type = entry.file_type().map_err(|source| InferlabError::Read {
                path: entry.path(),
                source,
            })?;
            if file_type.is_dir() {
                walk(&entry.path(), files)?;
            } else {
                files.push(entry.path());
            }
        }
        Ok(())
    }
    let mut files = Vec::new();
    walk(path, &mut files)?;
    files.sort();
    let mut hasher = Sha256::new();
    for file in &files {
        let relative = file.strip_prefix(path).unwrap_or(file);
        hasher.update(relative.display().to_string().as_bytes());
        hasher.update([0]);
        if file.is_symlink() {
            let target = fs::read_link(file).map_err(|source| InferlabError::Read {
                path: file.clone(),
                source,
            })?;
            hasher.update(target.display().to_string().as_bytes());
        } else {
            let bytes = fs::read(file).map_err(|source| InferlabError::Read {
                path: file.clone(),
                source,
            })?;
            hasher.update(&bytes);
        }
        hasher.update([0]);
    }
    Ok(format!("{:x}", hasher.finalize()))
}

/// PEP 503 package-name normalization for wheel/lock comparisons.
pub fn normalize_package_name(name: &str) -> String {
    let mut normalized = String::with_capacity(name.len());
    let mut previous_separator = false;
    for character in name.chars() {
        if matches!(character, '-' | '_' | '.') {
            if !previous_separator {
                normalized.push('-');
            }
            previous_separator = true;
        } else {
            normalized.push(character.to_ascii_lowercase());
            previous_separator = false;
        }
    }
    normalized
}

#[derive(Clone, Debug)]
pub struct PackageSpec {
    pub name: String,
    pub kind: PackageKind,
    pub url: Option<String>,
    pub sha256: Option<String>,
    pub editable: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PackageKind {
    Conda,
    Pypi,
}

/// Generate the reproducible build context: `Dockerfile`, entrypoint,
/// `conda-explicit.txt`, `pip-requirements.txt`, and `wheelhouse/`.
///
/// Fails closed when a source-backed package is neither replaced by a built
/// wheel nor resolved in the locked environment, so an image cannot silently
/// omit a required component.
pub fn prepare_context(
    inputs: &ContextInputs<'_>,
    packages: &[PackageSpec],
    source_packages: &[String],
) -> Result<PreparedContext, InferlabError> {
    let context_dir = inputs.context_dir.to_path_buf();
    fs::create_dir_all(&context_dir).map_err(|source| InferlabError::EnvironmentIo {
        path: context_dir.clone(),
        operation: "create build context directory",
        source,
    })?;

    let wheel_names: BTreeMap<String, &BuiltWheel> = inputs
        .built_wheels
        .iter()
        .map(|wheel| (normalize_package_name(&wheel.package), wheel))
        .collect();
    for package in source_packages {
        let normalized = normalize_package_name(package);
        let covered = wheel_names.contains_key(&normalized)
            || packages
                .iter()
                .any(|spec| !spec.editable && normalize_package_name(&spec.name) == normalized);
        if !covered {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "source-backed package {package:?} is neither built as a wheel nor resolved \
                     in the locked environment; the image would silently omit it"
                ),
            });
        }
    }

    let mut conda_lines = vec![
        "# Generated by Inferlab; hash-pinned explicit conda spec.".to_owned(),
        "@EXPLICIT".to_owned(),
    ];
    let mut pip_lines = vec!["# Generated by Inferlab; hash-pinned pypi requirements.".to_owned()];
    for spec in packages {
        if spec.editable || wheel_names.contains_key(&normalize_package_name(&spec.name)) {
            continue;
        }
        let (Some(url), Some(sha256)) = (&spec.url, &spec.sha256) else {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "locked package {:?} has no pinned url and sha256; \
                     the committed lock cannot reproduce it",
                    spec.name
                ),
            });
        };
        match spec.kind {
            PackageKind::Conda => conda_lines.push(format!("{url}#{sha256}")),
            PackageKind::Pypi => {
                pip_lines.push(format!("{} @ {url} --hash=sha256:{sha256}", spec.name));
            }
        }
    }

    let wheelhouse = context_dir.join("wheelhouse");
    fs::create_dir_all(&wheelhouse).map_err(|source| InferlabError::EnvironmentIo {
        path: wheelhouse.clone(),
        operation: "create wheelhouse directory",
        source,
    })?;
    let mut wheel_requirements =
        vec!["# Generated by Inferlab; locally built framework wheels.".to_owned()];
    for wheel in inputs.built_wheels {
        let target = wheelhouse.join(&wheel.filename);
        // The wheelhouse links from the immutable cache (published entries
        // are never overwritten) and is removed after a successful build, so
        // the record never retains the payload; copying is the cross-device
        // fallback.
        if fs::hard_link(&wheel.source_path, &target).is_err() {
            fs::copy(&wheel.source_path, &target).map_err(|source| {
                InferlabError::EnvironmentIo {
                    path: wheel.source_path.clone(),
                    operation: "copy built wheel into context",
                    source,
                }
            })?;
        }
        wheel_requirements.push(format!(
            "{} @ file:///wheelhouse/{} --hash=sha256:{}",
            wheel.package, wheel.filename, wheel.sha256
        ));
    }

    let dockerfile = render_dockerfile(inputs);
    let mut rendered = vec![
        ("conda-explicit.txt".to_owned(), conda_lines.join("\n")),
        ("pip-requirements.txt".to_owned(), pip_lines.join("\n")),
        (
            "wheel-requirements.txt".to_owned(),
            wheel_requirements.join("\n"),
        ),
        (
            "inferlab-entrypoint.sh".to_owned(),
            inputs.entrypoint.to_owned(),
        ),
        ("Dockerfile".to_owned(), dockerfile.clone()),
    ];
    if !inputs.checks.is_empty() {
        rendered.push((
            CHECKS_RUNNER_FILE.to_owned(),
            render_checks_runner(inputs.checks),
        ));
    }
    for (name, text) in &rendered {
        write_text(&context_dir.join(name), text)?;
    }

    // Declared scripts are committed workspace content copied by bytes; they
    // stay outside `rendered` because the generated-text portability guard
    // does not govern committed content ([[RFC-0007:C-IMAGE-BUILD]]).
    for (directory, scripts) in [
        (POSTPROCESS_CONTEXT_DIR, inputs.postprocess),
        (CHECKS_CONTEXT_DIR, inputs.checks),
    ] {
        if scripts.is_empty() {
            continue;
        }
        let script_dir = context_dir.join(directory);
        fs::create_dir_all(&script_dir).map_err(|source| InferlabError::EnvironmentIo {
            path: script_dir.clone(),
            operation: "create environment script directory",
            source,
        })?;
        for script in scripts {
            let target = script_dir.join(format!("{}.py", script.id));
            fs::write(&target, &script.bytes).map_err(|source| InferlabError::EnvironmentIo {
                path: target,
                operation: "write environment script",
                source,
            })?;
        }
    }

    Ok(PreparedContext {
        context_dir,
        dockerfile,
        rendered,
    })
}

/// Variable names that identify credential material
/// ([[RFC-0007:C-IMAGE-BUILD]]). Matched on `_`-separated name segments so
/// `HF_TOKEN` is excluded while `TOKENIZERS_PARALLELISM` projects. This is
/// best-effort protection for committed workspace content, not a secret
/// scanner; runtime credentials reach validation containers through the
/// per-machine `container.pass_env` binding instead.
fn credential_name(name: &str) -> bool {
    name.split('_').any(|segment| {
        matches!(
            segment.to_ascii_uppercase().as_str(),
            "TOKEN"
                | "TOKENS"
                | "SECRET"
                | "SECRETS"
                | "PASSWORD"
                | "PASSWD"
                | "CREDENTIAL"
                | "CREDENTIALS"
                | "APIKEY"
                | "KEY"
                | "PAT"
                | "AUTH"
                | "NETRC"
        )
    })
}

fn guard_self_reference(value: &str, name: &str) -> String {
    let braced = format!("${{{name}}}");
    let guarded = format!("${{{name}:-}}");
    let mut result = value.replace(&braced, &guarded);
    let bare = format!("${name}");
    let mut output = String::with_capacity(result.len());
    let mut rest = result.as_str();
    while let Some(position) = rest.find(&bare) {
        let after = &rest[position + bare.len()..];
        let boundary = after
            .chars()
            .next()
            .is_none_or(|next| !next.is_ascii_alphanumeric() && next != '_');
        output.push_str(&rest[..position]);
        if boundary {
            output.push_str(&guarded);
        } else {
            output.push_str(&bare);
        }
        rest = after;
    }
    output.push_str(rest);
    result = output;
    result
}

fn render_dockerfile(inputs: &ContextInputs<'_>) -> String {
    let base = &inputs.base_image;
    let digest = &inputs.base_image_digest;
    let reference = if base.contains('@') {
        base.to_string()
    } else {
        format!("{base}@{digest}")
    };
    let mut dockerfile = format!(
        "# Generated by {GENERATOR_IDENTITY}; do not edit.\n\
         FROM {reference}\n\
         USER root\n\
         COPY conda-explicit.txt /tmp/conda-explicit.txt\n\
         RUN micromamba create -y -p {ENV_PREFIX} -f /tmp/conda-explicit.txt \\\n\
         \x20   && micromamba clean -a -y\n\
         COPY pip-requirements.txt /tmp/pip-requirements.txt\n\
         RUN {ENV_PREFIX}/bin/python -m pip install --no-cache-dir --no-deps \\\n\
         \x20   --require-hashes -r /tmp/pip-requirements.txt\n\
         COPY wheelhouse/ /wheelhouse/\n\
         COPY wheel-requirements.txt /tmp/wheel-requirements.txt\n\
         RUN {ENV_PREFIX}/bin/python -m pip install --no-cache-dir --no-deps --no-index \\\n\
         \x20   --require-hashes -r /tmp/wheel-requirements.txt\n\
         COPY inferlab-entrypoint.sh {ENTRYPOINT_PATH}\n\
         RUN chmod 0755 {ENTRYPOINT_PATH}\n"
    );
    // Postprocess finishes the realization, then the checks gate it, both
    // through the entrypoint so the examined environment equals the runtime
    // activation ([[RFC-0002:C-ENVIRONMENT-CHECKS]]). A failed check fails
    // the build before an image identity exists; the generated runner frames
    // each check's exit into the builder log for attributable evidence.
    if !inputs.postprocess.is_empty() {
        dockerfile.push_str(&format!(
            "COPY {POSTPROCESS_CONTEXT_DIR}/ {POSTPROCESS_IMAGE_DIR}/\n"
        ));
        for script in inputs.postprocess {
            dockerfile.push_str(&format!(
                "RUN {ENTRYPOINT_PATH} python {POSTPROCESS_IMAGE_DIR}/{}.py\n",
                script.id
            ));
        }
    }
    if !inputs.checks.is_empty() {
        dockerfile.push_str(&format!(
            "COPY {CHECKS_CONTEXT_DIR}/ {CHECKS_IMAGE_DIR}/\n\
             COPY {CHECKS_RUNNER_FILE} {CHECKS_RUNNER_IMAGE_PATH}\n\
             RUN {ENTRYPOINT_PATH} /bin/sh {CHECKS_RUNNER_IMAGE_PATH}\n"
        ));
    }
    dockerfile.push_str(&format!("ENTRYPOINT [\"{ENTRYPOINT_PATH}\"]\n"));
    dockerfile
}

/// Portable-output guard ([[RFC-0007:C-IMAGE-BUILD]]): rendered context text
/// must not carry machine-private facts. Records keep exact values locally;
/// artifacts that leave the machine must exclude them by construction.
pub fn guard_portable_text(
    label: &str,
    text: &str,
    workspace: &LoadedWorkspace,
) -> Result<(), InferlabError> {
    let mut forbidden: Vec<(String, String)> = Vec::new();
    forbidden.push((
        "workspace root path".to_owned(),
        workspace.root.display().to_string(),
    ));
    for (id, weight) in &workspace.local.model_weights {
        if let Some(locator) = &weight.locator {
            forbidden.push((format!("model weight locator {id:?}"), locator.clone()));
        }
        for locator in weight.machine_locators.values() {
            forbidden.push((format!("model weight locator {id:?}"), locator.clone()));
        }
    }
    for (id, machine) in &workspace.local.machines {
        if machine.host != "127.0.0.1" && machine.host != "localhost" {
            forbidden.push((format!("machine host {id:?}"), machine.host.clone()));
        }
        if let crate::workspace::LaunchBinding::Ssh { target } = &machine.launch {
            forbidden.push((format!("machine SSH target {id:?}"), target.clone()));
        }
    }
    for (name, value) in forbidden {
        if !value.is_empty() && text.contains(&value) {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "{label} would carry machine-private fact ({name}); \
                     portable image outputs must exclude local facts by construction"
                ),
            });
        }
    }
    if text.contains("/home/") {
        return Err(InferlabError::ImageBuild {
            message: format!(
                "{label} would carry a host home-directory path; \
                 portable image outputs must exclude local facts by construction"
            ),
        });
    }
    Ok(())
}

fn write_text(path: &Path, content: &str) -> Result<(), InferlabError> {
    fs::write(path, content).map_err(|source| InferlabError::EnvironmentIo {
        path: path.to_path_buf(),
        operation: "write generated context file",
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::workspace::{
        LaunchBinding, LocalBindings, MachineBinding, ModelWeightBinding, WorkspaceConfig,
        WorkspaceSnapshot,
    };

    #[test]
    fn dockerfile_runs_postprocess_then_checks_through_the_entrypoint() {
        let script = |id: &str| ContextScript {
            id: id.to_owned(),
            bytes: b"print()".to_vec(),
        };
        let checks = [script("guard-a"), script("guard-b")];
        let postprocess = [script("finish")];
        let inputs = ContextInputs {
            context_dir: Path::new("unused"),
            base_image: "example.com/base:1",
            base_image_digest: "sha256:0000",
            entrypoint: "#!/bin/sh\n",
            built_wheels: &[],
            checks: &checks,
            postprocess: &postprocess,
        };
        let dockerfile = render_dockerfile(&inputs);
        let finish = dockerfile.find(
            "RUN /usr/local/bin/inferlab-entrypoint python /opt/inferlab-postprocess/finish.py",
        );
        let checks_layer = dockerfile.find(
            "RUN /usr/local/bin/inferlab-entrypoint /bin/sh /opt/inferlab-environment-checks.sh",
        );
        assert!(
            finish.is_some() && checks_layer.is_some(),
            "postprocess and check layers execute through the entrypoint: {dockerfile}"
        );
        assert!(
            finish < checks_layer,
            "postprocess finishes the realization before the checks gate it"
        );
        assert!(
            dockerfile.rfind("ENTRYPOINT") > checks_layer,
            "check layers execute before the final ENTRYPOINT directive"
        );

        let runner = render_checks_runner(&checks);
        let guard_a = runner.find("python /opt/inferlab-checks/guard-a.py");
        let guard_b = runner.find("python /opt/inferlab-checks/guard-b.py");
        assert!(
            guard_a.is_some() && guard_b.is_some() && guard_a < guard_b,
            "the runner executes every check in declaration order: {runner}"
        );
        assert!(
            runner.contains("printf 'INFERLAB-CHECK %s exit=%s\\n' 'guard-a' \"$status\"")
                && runner.contains("exit \"$failed\""),
            "each check frames its exit and any failure fails the layer: {runner}"
        );

        let bare = render_dockerfile(&ContextInputs {
            checks: &[],
            postprocess: &[],
            ..inputs
        });
        assert!(
            !bare.contains("/opt/inferlab-checks") && !bare.contains("/opt/inferlab-postprocess"),
            "environments without declarations render no script layers"
        );
    }

    #[test]
    fn entrypoint_contract_digest_tracks_rendered_text() -> Result<(), InferlabError> {
        let empty = render_entrypoint(&BTreeMap::new())?;
        let mut activation = BTreeMap::new();
        activation.insert("TORCH_CUDA_ARCH_LIST".to_owned(), "12.0".to_owned());
        let projected = render_entrypoint(&activation)?;
        assert_eq!(
            entrypoint_contract_digest(&empty.text),
            entrypoint_contract_digest(&empty.text)
        );
        assert_ne!(
            entrypoint_contract_digest(&empty.text),
            entrypoint_contract_digest(&projected.text)
        );
        Ok(())
    }

    #[test]
    fn entrypoint_rejects_shell_active_values() {
        for value in ["$(id)", "`id`", "broken\"quote", "back\\slash"] {
            let mut activation = BTreeMap::new();
            activation.insert("PROBE".to_owned(), (*value).to_owned());
            assert!(
                render_entrypoint(&activation).is_err(),
                "value {value:?} must be rejected"
            );
        }
    }

    #[test]
    fn entrypoint_projection_applies_the_v0_v1_rules() -> Result<(), InferlabError> {
        let mut activation = BTreeMap::new();
        activation.insert(
            "DG_JIT_NVCC_COMPILER".to_owned(),
            "$CONDA_PREFIX/bin/nvcc".to_owned(),
        );
        activation.insert(
            "DEEPGEMM_SRC_DIR".to_owned(),
            "$PIXI_PROJECT_ROOT/DeepGEMM".to_owned(),
        );
        activation.insert(
            "CPATH".to_owned(),
            "$CONDA_PREFIX/include:$CPATH".to_owned(),
        );
        activation.insert("PATH".to_owned(), "$CONDA_PREFIX/nvvm/bin:$PATH".to_owned());
        activation.insert("CONDA_PREFIX".to_owned(), "/somewhere/else".to_owned());
        let rendered = render_entrypoint(&activation)?;
        assert!(rendered.text.starts_with("#!/bin/sh"));
        assert!(
            rendered
                .text
                .contains("export CONDA_PREFIX=\"/opt/inferlab-env\"")
        );
        assert!(rendered.text.contains(
            "export DG_JIT_NVCC_COMPILER=\"${DG_JIT_NVCC_COMPILER:-$CONDA_PREFIX/bin/nvcc}\""
        ));
        assert!(
            rendered
                .text
                .contains("export CPATH=\"$CONDA_PREFIX/include:${CPATH:-}\"")
        );
        assert!(
            rendered
                .text
                .contains("export PATH=\"$CONDA_PREFIX/nvvm/bin:${PATH:-}\"")
        );
        assert!(!rendered.text.contains("DEEPGEMM_SRC_DIR"));
        assert_eq!(rendered.skipped, ["CONDA_PREFIX", "DEEPGEMM_SRC_DIR"]);
        Ok(())
    }

    #[test]
    fn entrypoint_excludes_credential_named_activation() -> Result<(), InferlabError> {
        let mut activation = BTreeMap::new();
        activation.insert("HF_TOKEN".to_owned(), "hf-credential-value".to_owned());
        activation.insert("AWS_SECRET_ACCESS_KEY".to_owned(), "aws-value".to_owned());
        activation.insert("DB_PASSWORD".to_owned(), "db-value".to_owned());
        activation.insert("TOKENIZERS_PARALLELISM".to_owned(), "false".to_owned());
        let rendered = render_entrypoint(&activation)?;
        for leak in [
            "HF_TOKEN",
            "hf-credential-value",
            "AWS_SECRET_ACCESS_KEY",
            "aws-value",
            "DB_PASSWORD",
            "db-value",
        ] {
            assert!(
                !rendered.text.contains(leak),
                "credential fact {leak:?} must not be projected"
            );
        }
        assert!(
            rendered
                .text
                .contains("export TOKENIZERS_PARALLELISM=\"${TOKENIZERS_PARALLELISM:-false}\""),
            "non-credential name segments must still project"
        );
        assert_eq!(
            rendered.skipped,
            ["AWS_SECRET_ACCESS_KEY", "DB_PASSWORD", "HF_TOKEN"]
        );
        Ok(())
    }

    #[test]
    fn unmodeled_activation_branches_are_rejected() -> Result<(), InferlabError> {
        let write_manifest = |content: &str| -> Result<tempfile::TempDir, InferlabError> {
            let dir = tempfile::tempdir().map_err(|source| InferlabError::EnvironmentIo {
                path: PathBuf::from("tempdir"),
                operation: "create test workspace",
                source,
            })?;
            fs::write(dir.path().join("pixi.toml"), content).map_err(|source| {
                InferlabError::EnvironmentIo {
                    path: dir.path().join("pixi.toml"),
                    operation: "write test manifest",
                    source,
                }
            })?;
            Ok(dir)
        };

        // Feature-scoped activation env is composed by the projection and is
        // legal; scripts under inert features or an excluded default feature
        // cannot bind and are legal too.
        for (label, manifest, environment) in [
            (
                "modeled workspace tables",
                "[activation.env]\nTORCH_CUDA_ARCH_LIST = \"12.0\"\n\
                 [target.linux-aarch64.activation.env]\nTORCH_CUDA_ARCH_LIST = \"9.0\"\n",
                "default",
            ),
            (
                "composed feature activation env",
                "[feature.cuda.activation.env]\nX = \"1\"\n[environments]\nvllm = [\"cuda\"]\n",
                "vllm",
            ),
            (
                "scripts under an inert feature",
                "[feature.dev.activation]\nscripts = [\"env.sh\"]\n\
                 [environments]\nvllm = [\"cuda\"]\n",
                "vllm",
            ),
            (
                "workspace scripts excluded by no-default-feature",
                "[activation]\nscripts = [\"env.sh\"]\n\
                 [environments]\nvllm = { features = [\"cuda\"], no-default-feature = true }\n",
                "vllm",
            ),
        ] {
            let dir = write_manifest(manifest)?;
            let verdict = guard_unmodeled_activation(dir.path(), "linux-64", environment);
            assert!(verdict.is_ok(), "{label} must stay legal: {verdict:?}");
        }

        for (label, manifest, environment) in [
            (
                "workspace activation scripts",
                "[activation]\nscripts = [\"env.sh\"]\n",
                "default",
            ),
            (
                "composed feature scripts",
                "[feature.cuda.activation]\nscripts = [\"env.sh\"]\n\
                 [environments]\nvllm = { features = [\"cuda\"] }\n",
                "vllm",
            ),
            (
                "composed feature target scripts",
                "[feature.cuda.target.linux-64.activation]\nscripts = [\"env.sh\"]\n\
                 [environments]\nvllm = [\"cuda\"]\n",
                "vllm",
            ),
        ] {
            let dir = write_manifest(manifest)?;
            assert!(
                guard_unmodeled_activation(dir.path(), "linux-64", environment).is_err(),
                "{label} must be rejected, not silently missed"
            );
        }
        Ok(())
    }

    /// The empirical pixi 0.71.2 precedence matrix, mirrored by the manual
    /// differential test in `tests/image.rs`: earlier-listed features win,
    /// target overrides untargeted within a feature, the default feature
    /// applies last unless excluded.
    const MERGE_PROBE_MANIFEST: &str = "\
[activation.env]\nX = \"default\"\nD = \"default-only\"\n\
[feature.a.activation.env]\nX = \"a\"\nA = \"a-only\"\n\
[feature.a.target.linux-64.activation.env]\nX = \"a-target\"\nT = \"a-target-only\"\n\
[feature.b.activation.env]\nX = \"b\"\nB = \"b-only\"\n\
[environments]\nab = [\"a\", \"b\"]\nba = [\"b\", \"a\"]\n\
nodef = { features = [\"a\"], no-default-feature = true }\n";

    #[test]
    fn activation_env_composes_features_per_pixi_precedence() -> Result<(), InferlabError> {
        let dir = tempfile::tempdir().map_err(|source| InferlabError::EnvironmentIo {
            path: PathBuf::from("tempdir"),
            operation: "create test workspace",
            source,
        })?;
        fs::write(dir.path().join("pixi.toml"), MERGE_PROBE_MANIFEST).map_err(|source| {
            InferlabError::EnvironmentIo {
                path: dir.path().join("pixi.toml"),
                operation: "write test manifest",
                source,
            }
        })?;
        let probe = |environment: &str| activation_env(dir.path(), "linux-64", environment);

        let ab = probe("ab")?;
        assert_eq!(
            ab.get("X").map(String::as_str),
            Some("a-target"),
            "earlier-listed feature wins; its target table wins within it"
        );
        assert_eq!(ab.get("A").map(String::as_str), Some("a-only"));
        assert_eq!(ab.get("B").map(String::as_str), Some("b-only"));
        assert_eq!(ab.get("D").map(String::as_str), Some("default-only"));
        assert_eq!(ab.get("T").map(String::as_str), Some("a-target-only"));

        let ba = probe("ba")?;
        assert_eq!(
            ba.get("X").map(String::as_str),
            Some("b"),
            "an earlier-listed feature's untargeted value beats a later feature's target value"
        );

        let nodef = probe("nodef")?;
        assert_eq!(nodef.get("X").map(String::as_str), Some("a-target"));
        assert_eq!(
            nodef.get("D"),
            None,
            "no-default-feature excludes the workspace tables"
        );

        let default = probe("default")?;
        assert_eq!(default.get("X").map(String::as_str), Some("default"));
        Ok(())
    }

    /// Differential tripwire against the real `pixi` on PATH: if a pixi
    /// upgrade ever changes feature-composition precedence, this fails loudly
    /// instead of letting the projection drift. Ignored by default (needs the
    /// real toolchain and repodata access); run with the manual suite.
    #[test]
    #[ignore]
    fn manual_activation_merge_matches_real_pixi() -> Result<(), InferlabError> {
        let dir = tempfile::tempdir().map_err(|source| InferlabError::EnvironmentIo {
            path: PathBuf::from("tempdir"),
            operation: "create probe workspace",
            source,
        })?;
        let manifest = format!(
            "[workspace]\nname = \"probe\"\nchannels = [\"conda-forge\"]\n\
             platforms = [\"linux-64\"]\n\n{MERGE_PROBE_MANIFEST}"
        );
        fs::write(dir.path().join("pixi.toml"), manifest).map_err(|source| {
            InferlabError::EnvironmentIo {
                path: dir.path().join("pixi.toml"),
                operation: "write probe manifest",
                source,
            }
        })?;
        let run = |args: &[&str]| -> Result<String, InferlabError> {
            let output = Command::new("pixi")
                .current_dir(dir.path())
                .args(args)
                .output()
                .map_err(|source| InferlabError::LaunchPixi {
                    action: "probe",
                    source,
                })?;
            if !output.status.success() {
                return Err(InferlabError::ImageBuild {
                    message: format!(
                        "pixi {args:?} failed: {}",
                        String::from_utf8_lossy(&output.stderr).trim()
                    ),
                });
            }
            Ok(String::from_utf8_lossy(&output.stdout).into_owned())
        };
        run(&["lock"])?;
        for environment in ["ab", "ba", "nodef"] {
            let projected = activation_env(dir.path(), "linux-64", environment)?;
            for variable in ["X", "A", "B", "D", "T"] {
                let observed = run(&[
                    "run",
                    "--no-progress",
                    "-e",
                    environment,
                    "--",
                    "sh",
                    "-c",
                    &format!("printenv {variable} || true"),
                ])?;
                let observed = observed.trim();
                let observed = (!observed.is_empty()).then_some(observed);
                assert_eq!(
                    projected.get(variable).map(String::as_str),
                    observed,
                    "pixi and the projection disagree on {variable} in {environment:?}: \
                     feature-composition precedence has drifted"
                );
            }
        }
        Ok(())
    }

    #[test]
    fn editable_identities_cover_external_paths_only() -> Result<(), InferlabError> {
        let scratch = tempfile::tempdir().map_err(|source| InferlabError::EnvironmentIo {
            path: PathBuf::from("tempdir"),
            operation: "create test workspace",
            source,
        })?;
        let external = scratch.path().join("sibling/pkg");
        fs::create_dir_all(external.join("src")).map_err(|source| {
            InferlabError::EnvironmentIo {
                path: external.clone(),
                operation: "create external package",
                source,
            }
        })?;
        fs::create_dir_all(external.join("__pycache__")).map_err(|source| {
            InferlabError::EnvironmentIo {
                path: external.clone(),
                operation: "create pycache",
                source,
            }
        })?;
        let write = |relative: &str, content: &str| -> Result<(), InferlabError> {
            fs::write(external.join(relative), content).map_err(|source| {
                InferlabError::EnvironmentIo {
                    path: external.join(relative),
                    operation: "write external file",
                    source,
                }
            })
        };
        write("src/module.py", "VALUE = 1\n")?;
        write("__pycache__/module.cpython-312.pyc", "derived")?;
        let root = scratch.path().join("workspace");
        fs::create_dir_all(&root).map_err(|source| InferlabError::EnvironmentIo {
            path: root.clone(),
            operation: "create workspace root",
            source,
        })?;

        let editable = |name: &str, url: &str| PackageSpec {
            name: name.to_owned(),
            kind: PackageKind::Pypi,
            url: Some(url.to_owned()),
            sha256: None,
            editable: true,
        };
        let packages = vec![
            editable("vllm", "./vllm"),
            editable("inferlab-adapter-sdk", "../sibling/pkg"),
            PackageSpec {
                name: "torch".to_owned(),
                kind: PackageKind::Pypi,
                url: Some("https://example/torch".to_owned()),
                sha256: Some("aa".to_owned()),
                editable: false,
            },
        ];
        let source_paths = [PathBuf::from("vllm")];

        let baseline = editable_identities(&root, &packages, &source_paths)?;
        assert_eq!(baseline.len(), 1, "only the external editable is keyed");
        assert!(baseline[0].starts_with("../sibling/pkg\u{1f}"));

        // Derived artifacts do not move the identity; source changes do.
        write("__pycache__/module.cpython-312.pyc", "different derived")?;
        assert_eq!(
            editable_identities(&root, &packages, &source_paths)?,
            baseline
        );
        write("src/module.py", "VALUE = 2\n")?;
        assert_ne!(
            editable_identities(&root, &packages, &source_paths)?,
            baseline
        );

        let no_url = vec![PackageSpec {
            name: "mystery".to_owned(),
            kind: PackageKind::Pypi,
            url: None,
            sha256: None,
            editable: true,
        }];
        assert!(
            editable_identities(&root, &no_url, &source_paths).is_err(),
            "an editable without a source path cannot be silently skipped"
        );
        Ok(())
    }

    #[test]
    fn locked_closure_digest_tracks_pinned_packages_only() {
        let pinned = |name: &str, sha: &str| PackageSpec {
            name: name.to_owned(),
            kind: PackageKind::Pypi,
            url: Some(format!("https://example/{name}")),
            sha256: Some(sha.to_owned()),
            editable: false,
        };
        let editable = PackageSpec {
            name: "vllm".to_owned(),
            kind: PackageKind::Pypi,
            url: None,
            sha256: None,
            editable: true,
        };
        let with_editable = vec![pinned("torch", "1"), editable.clone()];
        let without_editable = vec![pinned("torch", "1")];
        assert_eq!(
            locked_closure_digest(&with_editable),
            locked_closure_digest(&without_editable),
            "editable entries never move the closure digest"
        );
        let pin_changed = vec![pinned("torch", "2"), editable];
        assert_ne!(
            locked_closure_digest(&with_editable),
            locked_closure_digest(&pin_changed),
            "a pinned package change moves the closure digest"
        );
    }

    #[test]
    fn pixi_platform_maps_supported_targets() -> Result<(), InferlabError> {
        assert_eq!(pixi_platform("linux/amd64")?, "linux-64");
        assert_eq!(pixi_platform("linux/arm64")?, "linux-aarch64");
        assert!(pixi_platform("windows/amd64").is_err());
        Ok(())
    }

    fn guarded_workspace() -> LoadedWorkspace {
        let mut model_weights = BTreeMap::new();
        model_weights.insert(
            "dsv4".to_owned(),
            ModelWeightBinding {
                locator: Some("/secret/weights/dsv4".to_owned()),
                machine_locators: BTreeMap::new(),
            },
        );
        let mut machines = BTreeMap::new();
        machines.insert(
            "remote".to_owned(),
            MachineBinding {
                host: "gpu-node-7".to_owned(),
                devices: vec![0],
                ports: vec![8000],
                workspace: None,
                cache_root: None,
                container: None,
                launch: LaunchBinding::Ssh {
                    target: "operator@gpu-node-7".to_owned(),
                },
            },
        );
        LoadedWorkspace {
            root: PathBuf::from("/work/dsv4-workspace"),
            config: WorkspaceConfig {
                external_images: BTreeMap::new(),
                schema_version: 2,
                models: BTreeMap::new(),
                stacks: BTreeMap::new(),
                servers: BTreeMap::new(),
                evals: BTreeMap::new(),
                benches: BTreeMap::new(),
                workload_suites: BTreeMap::new(),
                recipes: BTreeMap::new(),
                images: BTreeMap::new(),
            },
            local: LocalBindings {
                adapter: crate::workspace::AdapterBinding::default(),
                default_placement: Some("local".to_owned()),
                model_weights,
                machines,
                placements: BTreeMap::new(),
                builders: BTreeMap::new(),
            },
            snapshot: WorkspaceSnapshot {
                revision: "0000".to_owned(),
                dirty: false,
                source_digest: "0000".to_owned(),
                source_exclusions: Vec::new(),
                revision_reproducible: true,
                pixi_manifest_sha256: "0000".to_owned(),
                pixi_lock_sha256: "0000".to_owned(),
            },
        }
    }

    #[test]
    fn guard_rejects_machine_private_facts_in_portable_text() {
        let workspace = guarded_workspace();
        for leak in [
            "FROM base\nCOPY /secret/weights/dsv4 /weights\n",
            "LABEL host=gpu-node-7\n",
            "ENV TARGET=operator@gpu-node-7\n",
            "WORKDIR /work/dsv4-workspace\n",
            "ENV STRAY=/home/operator/data\n",
        ] {
            assert!(
                guard_portable_text("test text", leak, &workspace).is_err(),
                "guard must reject {leak:?}"
            );
        }
    }

    #[test]
    fn guard_accepts_portable_text() -> Result<(), InferlabError> {
        let workspace = guarded_workspace();
        guard_portable_text(
            "test text",
            "FROM base@sha256:0000\nRUN micromamba create -y -p /opt/inferlab-env\n",
            &workspace,
        )
    }
}
