//! Filesystem materialization for generated runtime-only image build contexts
//! ([[RFC-0007:C-IMAGE-BUILD]]).

use super::entrypoint::{ENTRYPOINT_PATH, ENV_PREFIX};
use super::package_closure::{PackageKind, PackageSpec, normalize_package_name};
use crate::InferlabError;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

pub const GENERATOR_IDENTITY: &str = concat!("inferlab-image-context/", env!("CARGO_PKG_VERSION"));

/// Context-generation procedure identity ([[RFC-0007:C-IMAGE-BUILD]]): bump
/// when Dockerfile rendering, package projection, or context layout changes
/// without a crate version change. Enters the image content closure only —
/// context layout does not affect wheel bytes.
/// Epoch 2: environment postprocess and check RUN layers execute through the
/// entrypoint inside assembly ([[RFC-0002:C-ENVIRONMENT-CHECKS]]).
/// Epoch 3: checks execute through a generated runner that frames per-check
/// results into the builder log, so a failed build still attributes which
/// checks ran and how they exited.
pub const IMAGE_CONTEXT_EPOCH: u32 = 3;

/// The framing prefix the generated check runner emits per check; the
/// builder log is scanned for it to reconstruct per-check evidence.
pub const CHECK_MARKER: &str = "INFERLAB-CHECK";

const CHECKS_CONTEXT_DIR: &str = "environment-checks";
const POSTPROCESS_CONTEXT_DIR: &str = "environment-postprocess";
const CHECKS_IMAGE_DIR: &str = "/opt/inferlab-checks";
const POSTPROCESS_IMAGE_DIR: &str = "/opt/inferlab-postprocess";
const CHECKS_RUNNER_FILE: &str = "inferlab-environment-checks.sh";
const CHECKS_RUNNER_IMAGE_PATH: &str = "/opt/inferlab-environment-checks.sh";

pub struct ContextInputs<'a> {
    pub context_dir: &'a Path,
    pub base_image: &'a str,
    pub base_image_digest: &'a str,
    /// The rendered activation entrypoint script.
    pub entrypoint: &'a str,
    /// Wheels built from the stack sources, copied by bytes.
    pub built_wheels: &'a [BuiltWheel],
    /// Declared environment checks, copied by bytes and executed as RUN
    /// layers through the entrypoint ([[RFC-0002:C-ENVIRONMENT-CHECKS]]).
    pub checks: &'a [ContextScript],
    /// Declared image-realization postprocess steps, executed before the
    /// checks.
    pub postprocess: &'a [ContextScript],
}

/// A committed workspace script copied into the frozen context. Committed
/// content stays under the workspace author's secret posture, not the
/// generated-text portability guard.
#[derive(Clone, Debug)]
pub struct ContextScript {
    pub id: String,
    pub bytes: Vec<u8>,
}

#[derive(Clone, Debug)]
pub struct BuiltWheel {
    pub package: String,
    pub filename: String,
    pub source_path: PathBuf,
    pub sha256: String,
}

#[derive(Clone, Debug)]
pub struct PreparedContext {
    pub context_dir: PathBuf,
    pub dockerfile: String,
    /// Every rendered text destined for the image: checked by the
    /// portable-output guard before assembly.
    pub rendered: Vec<(String, String)>,
}

/// Generate the reproducible build context: `Dockerfile`, entrypoint,
/// `conda-explicit.txt`, `pip-requirements.txt`, and `wheelhouse/`.
///
/// Fails closed when a source-backed package is neither replaced by a built
/// wheel nor resolved in the locked environment, so an image cannot silently
/// omit a required component.
pub fn prepare_context(
    inputs: &ContextInputs<'_>,
    packages: &[PackageSpec],
    source_packages: &[String],
) -> Result<PreparedContext, InferlabError> {
    let context_dir = inputs.context_dir.to_path_buf();
    fs::create_dir_all(&context_dir).map_err(|source| InferlabError::EnvironmentIo {
        path: context_dir.clone(),
        operation: "create build context directory",
        source,
    })?;

    let wheel_names: BTreeMap<String, &BuiltWheel> = inputs
        .built_wheels
        .iter()
        .map(|wheel| (normalize_package_name(&wheel.package), wheel))
        .collect();
    for package in source_packages {
        let normalized = normalize_package_name(package);
        let covered = wheel_names.contains_key(&normalized)
            || packages
                .iter()
                .any(|spec| !spec.editable && normalize_package_name(&spec.name) == normalized);
        if !covered {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "source-backed package {package:?} is neither built as a wheel nor resolved \
                     in the locked environment; the image would silently omit it"
                ),
            });
        }
    }

    let mut conda_lines = vec![
        "# Generated by Inferlab; hash-pinned explicit conda spec.".to_owned(),
        "@EXPLICIT".to_owned(),
    ];
    let mut pip_lines = vec!["# Generated by Inferlab; hash-pinned pypi requirements.".to_owned()];
    for spec in packages {
        if spec.editable || wheel_names.contains_key(&normalize_package_name(&spec.name)) {
            continue;
        }
        let (Some(url), Some(sha256)) = (&spec.url, &spec.sha256) else {
            return Err(InferlabError::ImageBuild {
                message: format!(
                    "locked package {:?} has no pinned url and sha256; \
                     the committed lock cannot reproduce it",
                    spec.name
                ),
            });
        };
        match spec.kind {
            PackageKind::Conda => conda_lines.push(format!("{url}#{sha256}")),
            PackageKind::Pypi => {
                pip_lines.push(format!("{} @ {url} --hash=sha256:{sha256}", spec.name));
            }
        }
    }

    let wheelhouse = context_dir.join("wheelhouse");
    fs::create_dir_all(&wheelhouse).map_err(|source| InferlabError::EnvironmentIo {
        path: wheelhouse.clone(),
        operation: "create wheelhouse directory",
        source,
    })?;
    let mut wheel_requirements =
        vec!["# Generated by Inferlab; locally built framework wheels.".to_owned()];
    for wheel in inputs.built_wheels {
        let target = wheelhouse.join(&wheel.filename);
        // The wheelhouse links from the immutable cache (published entries
        // are never overwritten) and is removed after a successful build, so
        // the record never retains the payload; copying is the cross-device
        // fallback.
        if fs::hard_link(&wheel.source_path, &target).is_err() {
            fs::copy(&wheel.source_path, &target).map_err(|source| {
                InferlabError::EnvironmentIo {
                    path: wheel.source_path.clone(),
                    operation: "copy built wheel into context",
                    source,
                }
            })?;
        }
        wheel_requirements.push(format!(
            "{} @ file:///wheelhouse/{} --hash=sha256:{}",
            wheel.package, wheel.filename, wheel.sha256
        ));
    }

    let dockerfile = render_dockerfile(inputs);
    let mut rendered = vec![
        ("conda-explicit.txt".to_owned(), conda_lines.join("\n")),
        ("pip-requirements.txt".to_owned(), pip_lines.join("\n")),
        (
            "wheel-requirements.txt".to_owned(),
            wheel_requirements.join("\n"),
        ),
        (
            "inferlab-entrypoint.sh".to_owned(),
            inputs.entrypoint.to_owned(),
        ),
        ("Dockerfile".to_owned(), dockerfile.clone()),
    ];
    if !inputs.checks.is_empty() {
        rendered.push((
            CHECKS_RUNNER_FILE.to_owned(),
            render_checks_runner(inputs.checks),
        ));
    }
    for (name, text) in &rendered {
        write_text(&context_dir.join(name), text)?;
    }

    // Declared scripts are committed workspace content copied by bytes; they
    // stay outside `rendered` because the generated-text portability guard
    // does not govern committed content ([[RFC-0007:C-IMAGE-BUILD]]).
    for (directory, scripts) in [
        (POSTPROCESS_CONTEXT_DIR, inputs.postprocess),
        (CHECKS_CONTEXT_DIR, inputs.checks),
    ] {
        if scripts.is_empty() {
            continue;
        }
        let script_dir = context_dir.join(directory);
        fs::create_dir_all(&script_dir).map_err(|source| InferlabError::EnvironmentIo {
            path: script_dir.clone(),
            operation: "create environment script directory",
            source,
        })?;
        for script in scripts {
            let target = script_dir.join(format!("{}.py", script.id));
            fs::write(&target, &script.bytes).map_err(|source| InferlabError::EnvironmentIo {
                path: target,
                operation: "write environment script",
                source,
            })?;
        }
    }

    Ok(PreparedContext {
        context_dir,
        dockerfile,
        rendered,
    })
}

/// The generated in-image check runner ([[RFC-0002:C-ENVIRONMENT-CHECKS]]):
/// every declared check executes, each frames its exit into the builder log,
/// and the layer fails when any check failed — so a failed build still says
/// which checks ran and how they exited, while an image can only exist with
/// every check green.
fn render_checks_runner(checks: &[ContextScript]) -> String {
    let mut lines = vec![
        format!("#!/bin/sh\n# Generated by {GENERATOR_IDENTITY}; do not edit."),
        "failed=0".to_owned(),
    ];
    for script in checks {
        lines.push(format!("python {CHECKS_IMAGE_DIR}/{}.py", script.id));
        lines.push("status=$?".to_owned());
        lines.push(format!(
            "printf '{CHECK_MARKER} %s exit=%s\\n' '{}' \"$status\"",
            script.id
        ));
        lines.push("if [ \"$status\" -ne 0 ]; then failed=1; fi".to_owned());
    }
    lines.push("exit \"$failed\"".to_owned());
    lines.push(String::new());
    lines.join("\n")
}

fn render_dockerfile(inputs: &ContextInputs<'_>) -> String {
    let base = &inputs.base_image;
    let digest = &inputs.base_image_digest;
    let reference = if base.contains('@') {
        base.to_string()
    } else {
        format!("{base}@{digest}")
    };
    let mut dockerfile = format!(
        "# Generated by {GENERATOR_IDENTITY}; do not edit.\n\
         FROM {reference}\n\
         USER root\n\
         COPY conda-explicit.txt /tmp/conda-explicit.txt\n\
         RUN micromamba create -y -p {ENV_PREFIX} -f /tmp/conda-explicit.txt \\\n\
         \x20   && micromamba clean -a -y\n\
         COPY pip-requirements.txt /tmp/pip-requirements.txt\n\
         RUN {ENV_PREFIX}/bin/python -m pip install --no-cache-dir --no-deps \\\n\
         \x20   --require-hashes -r /tmp/pip-requirements.txt\n\
         COPY wheelhouse/ /wheelhouse/\n\
         COPY wheel-requirements.txt /tmp/wheel-requirements.txt\n\
         RUN {ENV_PREFIX}/bin/python -m pip install --no-cache-dir --no-deps --no-index \\\n\
         \x20   --require-hashes -r /tmp/wheel-requirements.txt\n\
         COPY inferlab-entrypoint.sh {ENTRYPOINT_PATH}\n\
         RUN chmod 0755 {ENTRYPOINT_PATH}\n"
    );
    // Postprocess finishes the realization, then the checks gate it, both
    // through the entrypoint so the examined environment equals the runtime
    // activation ([[RFC-0002:C-ENVIRONMENT-CHECKS]]). A failed check fails
    // the build before an image identity exists; the generated runner frames
    // each check's exit into the builder log for attributable evidence.
    if !inputs.postprocess.is_empty() {
        dockerfile.push_str(&format!(
            "COPY {POSTPROCESS_CONTEXT_DIR}/ {POSTPROCESS_IMAGE_DIR}/\n"
        ));
        for script in inputs.postprocess {
            dockerfile.push_str(&format!(
                "RUN {ENTRYPOINT_PATH} python {POSTPROCESS_IMAGE_DIR}/{}.py\n",
                script.id
            ));
        }
    }
    if !inputs.checks.is_empty() {
        dockerfile.push_str(&format!(
            "COPY {CHECKS_CONTEXT_DIR}/ {CHECKS_IMAGE_DIR}/\n\
             COPY {CHECKS_RUNNER_FILE} {CHECKS_RUNNER_IMAGE_PATH}\n\
             RUN {ENTRYPOINT_PATH} /bin/sh {CHECKS_RUNNER_IMAGE_PATH}\n"
        ));
    }
    dockerfile.push_str(&format!("ENTRYPOINT [\"{ENTRYPOINT_PATH}\"]\n"));
    dockerfile
}

fn write_text(path: &Path, content: &str) -> Result<(), InferlabError> {
    fs::write(path, content).map_err(|source| InferlabError::EnvironmentIo {
        path: path.to_path_buf(),
        operation: "write generated context file",
        source,
    })
}

#[cfg(test)]
mod tests {
    use super::{ContextInputs, ContextScript, render_checks_runner, render_dockerfile};
    use std::path::Path;

    #[test]
    fn dockerfile_runs_postprocess_then_checks_through_the_entrypoint() {
        let script = |id: &str| ContextScript {
            id: id.to_owned(),
            bytes: b"print()".to_vec(),
        };
        let checks = [script("guard-a"), script("guard-b")];
        let postprocess = [script("finish")];
        let inputs = ContextInputs {
            context_dir: Path::new("unused"),
            base_image: "example.com/base:1",
            base_image_digest: "sha256:0000",
            entrypoint: "#!/bin/sh\n",
            built_wheels: &[],
            checks: &checks,
            postprocess: &postprocess,
        };

        let dockerfile = render_dockerfile(&inputs);
        assert!(
            dockerfile.contains(concat!(
                "RUN micromamba create -y -p /opt/inferlab-env -f /tmp/conda-explicit.txt \\\n",
                "    && micromamba clean -a -y"
            )),
            "the conda installation command keeps its valid continuation: {dockerfile}"
        );
        assert!(
            dockerfile.contains(concat!(
                "RUN /opt/inferlab-env/bin/python -m pip install --no-cache-dir --no-deps \\\n",
                "    --require-hashes -r /tmp/pip-requirements.txt"
            )),
            "the pip installation command keeps its valid continuation: {dockerfile}"
        );
        let finish = dockerfile.find(
            "RUN /usr/local/bin/inferlab-entrypoint python /opt/inferlab-postprocess/finish.py",
        );
        let checks_layer = dockerfile.find(
            "RUN /usr/local/bin/inferlab-entrypoint /bin/sh /opt/inferlab-environment-checks.sh",
        );
        assert!(
            finish.is_some() && checks_layer.is_some(),
            "postprocess and check layers execute through the entrypoint: {dockerfile}"
        );
        assert!(
            finish < checks_layer,
            "postprocess finishes the realization before the checks gate it"
        );
        assert!(
            dockerfile.rfind("ENTRYPOINT") > checks_layer,
            "check layers execute before the final ENTRYPOINT directive"
        );

        let runner = render_checks_runner(&checks);
        let guard_a = runner.find("python /opt/inferlab-checks/guard-a.py");
        let guard_b = runner.find("python /opt/inferlab-checks/guard-b.py");
        assert!(
            guard_a.is_some() && guard_b.is_some() && guard_a < guard_b,
            "the runner executes every check in declaration order: {runner}"
        );
        assert!(
            runner.contains("printf 'INFERLAB-CHECK %s exit=%s\\n' 'guard-a' \"$status\"")
                && runner.contains("exit \"$failed\""),
            "each check frames its exit and any failure fails the layer: {runner}"
        );

        let bare = render_dockerfile(&ContextInputs {
            checks: &[],
            postprocess: &[],
            ..inputs
        });
        assert!(
            !bare.contains("/opt/inferlab-checks") && !bare.contains("/opt/inferlab-postprocess"),
            "environments without declarations render no script layers"
        );
    }
}
