# Rust wire source: crates/inferlab-protocol/src/wire.rs
# @generated by datamodel-codegen:
#   filename:  adapter-protocol-v7.schema.json

from enum import StrEnum
from typing import Annotated, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AdapterErrorCode(StrEnum):
    invalid_request = 'invalid_request'
    unsupported_protocol_version = 'unsupported_protocol_version'
    invalid_settings = 'invalid_settings'
    internal = 'internal'
    unsupported_operation = 'unsupported_operation'


class AllocationLaunchLocal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['local'] = 'local'


class AllocationLaunchSsh(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ssh'] = 'ssh'
    target: str


class AllocationLaunch(RootModel[AllocationLaunchLocal | AllocationLaunchSsh]):
    root: Annotated[
        AllocationLaunchLocal | AllocationLaunchSsh,
        Field(
            description='The machine-local launch channel selected by the control plane.'
        ),
    ]


class BenchDatasetCacheState(StrEnum):
    missing = 'missing'
    present = 'present'


class BenchDatasetCatalogInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache_path: str
    cache_state: BenchDatasetCacheState
    license: str
    materialization_identity: str
    sha256: str
    source_format: str
    upstream_identity: str
    url: str


class BenchDatasetInput(RootModel[Literal['sharegpt']]):
    root: Annotated[
        Literal['sharegpt'],
        Field(description='Release-qualified public Bench datasets.'),
    ] = 'sharegpt'


class BenchLoadInputConcurrencyLimited(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int, Field(ge=0)]
    kind: Literal['concurrency_limited'] = 'concurrency_limited'


class BenchLoadInputRequestRateLimited(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    burstiness: float | None = None
    kind: Literal['request_rate_limited'] = 'request_rate_limited'
    request_rate: float


class BenchLoadInputUnboundedRequestRate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['unbounded_request_rate'] = 'unbounded_request_rate'


class BenchLoadInput(
    RootModel[
        BenchLoadInputConcurrencyLimited
        | BenchLoadInputRequestRateLimited
        | BenchLoadInputUnboundedRequestRate
    ]
):
    root: Annotated[
        BenchLoadInputConcurrencyLimited
        | BenchLoadInputRequestRateLimited
        | BenchLoadInputUnboundedRequestRate,
        Field(description='How a Bench case paces its requests.'),
    ]


class BenchPopulationInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entries: Annotated[int, Field(ge=0)]
    path: str
    sha256: str
    tpot_applicable: bool


class BenchRequestSloInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    minimum_good_request_ratio: float
    request_latency_ms: float | None = None
    tpot_ms: float | None = None
    ttft_ms: float | None = None


class BenchRequestSloResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    good_request_ratio: float
    good_requests: Annotated[int, Field(ge=0)]
    goodput: float
    native_aggregate_good_request_count: Annotated[int | None, Field(ge=0)] = None
    native_aggregate_good_request_count_consistent: bool | None = None
    profiling_duration_seconds: float
    profiling_duration_source: str
    request_count_reconciled: bool


class BenchRequestSourceInputRandom(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input_tokens: Annotated[int, Field(ge=0)]
    kind: Literal['random'] = 'random'
    output_tokens: Annotated[int, Field(ge=0)]


class BenchRequestSourceInputDataset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    catalog: BenchDatasetCatalogInput
    dataset: BenchDatasetInput
    kind: Literal['dataset'] = 'dataset'
    max_input_tokens: Annotated[int, Field(ge=0)]
    output_tokens: Annotated[int | None, Field(ge=0)] = None


class BenchRequestSourceInput(
    RootModel[BenchRequestSourceInputRandom | BenchRequestSourceInputDataset]
):
    root: Annotated[
        BenchRequestSourceInputRandom | BenchRequestSourceInputDataset,
        Field(
            description='One closed request origin lowered by Inferlab for the Bench runtime.'
        ),
    ]


class BenchTokenCountSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    maximum: Annotated[int, Field(ge=0)]
    mean: float
    minimum: Annotated[int, Field(ge=0)]


class CaptureWindowControlEndpoint(StrEnum):
    replica_entry = 'replica_entry'
    gateway = 'gateway'


class ClientStatus(StrEnum):
    succeeded = 'succeeded'
    failed = 'failed'


class EndpointAssignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: str
    port: Annotated[int, Field(ge=0, le=65535)]


class EndpointProtocol(RootModel[Literal['http']]):
    root: Annotated[
        Literal['http'],
        Field(description='The application protocol a workload endpoint speaks.'),
    ] = 'http'


class EvalDefinitionInputOpenaiSmoke(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['openai_smoke'] = 'openai_smoke'
    max_tokens: Annotated[int, Field(ge=0)]
    prompt: str
    timeout_seconds: Annotated[int, Field(ge=0)]


class EvalFailureKind(StrEnum):
    task_resolution = 'task_resolution'
    probe_tokenizer = 'probe_tokenizer'
    probe_transport = 'probe_transport'
    probe_http = 'probe_http'
    probe_malformed_response = 'probe_malformed_response'
    probe_generated_only_logprobs = 'probe_generated_only_logprobs'
    probe_tokenizer_alignment = 'probe_tokenizer_alignment'
    metric_normalization = 'metric_normalization'


class EvalMetricComparison(StrEnum):
    at_least = 'at_least'
    at_most = 'at_most'


class EvalMetricGateConclusion(StrEnum):
    passed = 'passed'
    failed = 'failed'


class EvalNormalizedMetric(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    filter: str | None = None
    higher_is_better: bool
    metric: str
    native_metric_key: str
    source_identity: str
    value: float


class EvalTaskSourceInputBuiltIn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['built_in'] = 'built_in'
    name: str


class EvalTaskSourceInputBundled(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dataset_asset_sha256: str
    kind: Literal['bundled'] = 'bundled'
    name: str
    path: str
    prompt_asset_sha256: str
    scorer_sha256: str
    task_closure_sha256: str
    task_definition_sha256: str
    task_identity: str


class EvalTaskSourceInputWorkspaceYaml(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['workspace_yaml'] = 'workspace_yaml'
    path: str


class EvalTaskSourceInput(
    RootModel[
        EvalTaskSourceInputBuiltIn
        | EvalTaskSourceInputBundled
        | EvalTaskSourceInputWorkspaceYaml
    ]
):
    root: Annotated[
        EvalTaskSourceInputBuiltIn
        | EvalTaskSourceInputBundled
        | EvalTaskSourceInputWorkspaceYaml,
        Field(
            description='The resolved lm-eval task source consumed by the release-owned Eval runner.'
        ),
    ]


class EvalTrialSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed_trials: Annotated[int, Field(ge=0)]
    higher_is_better: bool
    issued_trials: Annotated[int, Field(ge=0)]
    pass_rate: float | None = None
    passed_trials: Annotated[int, Field(ge=0)]
    per_trial_filter: str | None = None
    per_trial_metric: str
    request_failure_trials: Annotated[int, Field(ge=0)]
    requested_trials: Annotated[int, Field(ge=0)]
    unissued_trials: Annotated[int, Field(ge=0)]


class FrontendGatewayComponent(RootModel[Literal['gateway']]):
    root: Annotated[
        Literal['gateway'],
        Field(
            description='The literal first member of every closed frontend component binding.'
        ),
    ] = 'gateway'


class FrontendHandoff(RootModel[Literal['in_process']]):
    root: Annotated[
        Literal['in_process'],
        Field(
            description='The currently demonstrated Gateway-to-P/D Router handoff is internal to\none fused frontend process.'
        ),
    ] = 'in_process'


class FrontendPdRouterComponent(RootModel[Literal['pd_router']]):
    root: Annotated[
        Literal['pd_router'],
        Field(
            description='The literal second member of the fused P/D frontend component binding.'
        ),
    ] = 'pd_router'


class FrontendProcessRole(RootModel[Literal['gateway']]):
    root: Annotated[
        Literal['gateway'],
        Field(
            description='The one canonical process role available to a protocol-v7 frontend.'
        ),
    ] = 'gateway'


class GatewayFrontendBinding(RootModel[list[FrontendGatewayComponent]]):
    root: Annotated[
        list[FrontendGatewayComponent],
        Field(
            description='The stable schema branch for a Gateway-only frontend binding.',
            max_length=1,
            min_length=1,
        ),
    ]


class GatewayPdRouterFrontendBinding(
    RootModel[tuple[FrontendGatewayComponent, FrontendPdRouterComponent]]
):
    root: Annotated[
        tuple[FrontendGatewayComponent, FrontendPdRouterComponent],
        Field(
            description='The stable schema branch for a fused Gateway and P/D Router binding.'
        ),
    ]


class GatewayTargetEngine(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['engine'] = 'engine'
    role: str


class GatewayTargetPdRouter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pd_router'] = 'pd_router'


class GatewayTarget(RootModel[GatewayTargetEngine | GatewayTargetPdRouter]):
    root: Annotated[
        GatewayTargetEngine | GatewayTargetPdRouter,
        Field(description='The target a Gateway forwards accepted public requests to.'),
    ]


class HttpMethod(RootModel[Literal['post']]):
    root: Annotated[
        Literal['post'], Field(description='The HTTP method of an [`HttpActionSpec`].')
    ] = 'post'


class IntegrationIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapter_id: str
    adapter_version: str
    framework: str
    framework_version: str


class KvTransferMechanism(StrEnum):
    mooncake = 'mooncake'
    nixl = 'nixl'


class LaunchFileDeclaration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    relative_path: str
    sha256: str
    text: str


class MeasurementModelInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locator: str
    served_name: str


class ParallelismAttention(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context_parallel_size: Annotated[int | None, Field(ge=1)] = None
    data_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ParallelismExperts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_parallel_size: Annotated[int | None, Field(ge=1)] = None
    dense_tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None
    expert_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ParallelismOuter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pipeline_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class PdRoutingPolicies(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decode: str
    prefill: str


class ProcessSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: list[str]
    env: dict[str, str]


class ProtocolVersion(RootModel[Literal['7']]):
    root: Annotated[
        Literal['7'],
        Field(
            description='The shared protocol version used by framework integrations and release-owned\nmeasurement clients. The only accepted value is `7` (serialized as the\nstring `"7"`); a mismatch is rejected before lowering.'
        ),
    ] = '7'


class RawArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: str
    name: str
    path: str


class ReadinessProbeHttp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['http'] = 'http'
    path: str


class ReadinessProbeProcessAlive(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['process_alive'] = 'process_alive'


class RenderInputDeclaration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_path: str


class RenderSource(StrEnum):
    control_plane = 'control_plane'
    integration = 'integration'


class RenderedServeProcessModelRank(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: ProcessSpec
    kind: Literal['model_rank'] = 'model_rank'
    launch_files: list[LaunchFileDeclaration]
    process: str
    rank: Annotated[int, Field(ge=0)]
    rank_count: Annotated[int, Field(ge=0)]
    replica: Annotated[int, Field(ge=0)]
    role: str


class ServeModelInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    served_name: str


class Device(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class ServeRoleKind(StrEnum):
    serve = 'serve'
    prefill = 'prefill'
    decode = 'decode'


class ServeRoleLinkRequestRouting(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['request_routing'] = 'request_routing'
    source: str
    targets: list[str]


class ServeRoleLinkKvTransfer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['kv_transfer'] = 'kv_transfer'
    mechanism: KvTransferMechanism
    source: str
    target: str


class ServeRoleLinkBootstrap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['bootstrap'] = 'bootstrap'
    port: str
    source: str
    target: str


class ServeRoleLinkSideChannel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['side_channel'] = 'side_channel'
    port: str
    source: str
    target: str


class ServeRoleLink(
    RootModel[
        ServeRoleLinkRequestRouting
        | ServeRoleLinkKvTransfer
        | ServeRoleLinkBootstrap
        | ServeRoleLinkSideChannel
    ]
):
    root: Annotated[
        ServeRoleLinkRequestRouting
        | ServeRoleLinkKvTransfer
        | ServeRoleLinkBootstrap
        | ServeRoleLinkSideChannel,
        Field(
            description='A directed link between serve roles the integration declares as part of the\ntopology.'
        ),
    ]


class ServeTopology(StrEnum):
    single = 'single'
    prefill_decode = 'prefill_decode'


class SettingValue(
    RootModel[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]]
    ]
):
    root: Annotated[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]],
        Field(
            description='A framework-specific server setting value carried as structured JSON data\n(never a pre-rendered shell fragment) across the integration boundary.'
        ),
    ]


class SuppliedRenderInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sha256: str
    source_path: str
    text: str


class TargetEndpointScheme(StrEnum):
    http = 'http'
    grpc = 'grpc'


class AdapterError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: AdapterErrorCode
    message: str


class AdapterResponseError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: AdapterError
    protocol_version: ProtocolVersion
    status: Literal['error'] = 'error'


class BenchCaseInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    load_shape: BenchLoadInput
    request_count: Annotated[int, Field(ge=0)]
    warmup_request_count: Annotated[int, Field(ge=0)] = 0


class BenchClientResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    completed_requests: Annotated[int, Field(ge=0)]
    error: str | None = None
    failed_requests: Annotated[int, Field(ge=0)]
    metrics: dict[str, float]
    native_command: list[str]
    native_exit_code: int | None = None
    normalization_schema: str
    raw_artifacts: list[RawArtifact]
    request_slo: BenchRequestSloResult | None = None
    schema_version: Annotated[
        int,
        Field(
            description='Result envelope version; clients write `1`. The measurement runtime\nrejects a bench result whose version is not `1`.',
            ge=0,
        ),
    ]
    status: ClientStatus


class BenchDatasetPreparationRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    model: MeasurementModelInput
    protocol_version: ProtocolVersion
    request_body: Annotated[dict[str, SettingValue], Field(validate_default=True)] = {}
    request_source: BenchRequestSourceInput
    required_entries: Annotated[int, Field(ge=0)]
    seed: Annotated[int, Field(ge=0)]
    source_path: str


class BenchDatasetPreparationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    admitted_entries: Annotated[int, Field(ge=0)]
    candidate_entries: Annotated[int, Field(ge=0)]
    error: str | None = None
    evidence_path: str | None = None
    ineligible_entries: Annotated[int, Field(ge=0)]
    ineligible_reasons: dict[str, int] = {}
    input_tokens: BenchTokenCountSummary | None = None
    materialization_identity: str
    output_tokens: BenchTokenCountSummary | None = None
    population: BenchPopulationInput | None = None
    requested_entries: Annotated[int, Field(ge=0)]
    schema_version: Annotated[int, Field(ge=0)]
    status: ClientStatus


class BenchDefinitionInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request_body: Annotated[dict[str, SettingValue], Field(validate_default=True)] = {}
    request_slo: BenchRequestSloInput | None = None
    request_source: BenchRequestSourceInput
    reset_prefix_cache: bool = False
    seed: Annotated[int, Field(ge=0)]
    timeout_seconds: Annotated[int, Field(ge=0)]


class ClientEndpointInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_completions_path: str
    completions_path: str
    host: str
    port: Annotated[int, Field(ge=0, le=65535)]
    protocol: EndpointProtocol


class EvalDefinitionInputLmEval(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    concurrency: Annotated[int | None, Field(ge=0)] = None
    few_shot: Annotated[int | None, Field(ge=0)] = None
    kind: Literal['lm_eval'] = 'lm_eval'
    limit: Annotated[int | None, Field(ge=0)] = None
    max_tokens: Annotated[int | None, Field(ge=0)] = None
    metric: str
    metric_filter: str | None = None
    request_body: Annotated[dict[str, SettingValue], Field(validate_default=True)] = {}
    seed: Annotated[int | None, Field(ge=0)] = None
    task: EvalTaskSourceInput
    threshold: float
    timeout_seconds: Annotated[int, Field(ge=0)]
    trials: Annotated[int, Field(ge=0)]


class EvalDefinitionInput(
    RootModel[EvalDefinitionInputOpenaiSmoke | EvalDefinitionInputLmEval]
):
    root: Annotated[
        EvalDefinitionInputOpenaiSmoke | EvalDefinitionInputLmEval,
        Field(
            description='The measurement an Eval client runs against the workload endpoint.'
        ),
    ]


class EvalMetricGate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    comparison: EvalMetricComparison
    conclusion: EvalMetricGateConclusion
    metric: EvalNormalizedMetric
    threshold: float


class FrontendCoRendering(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_role: FrontendProcessRole


class FrontendComponents(
    RootModel[GatewayFrontendBinding | GatewayPdRouterFrontendBinding]
):
    root: Annotated[
        GatewayFrontendBinding | GatewayPdRouterFrontendBinding,
        Field(
            description='The only two frontend bindings protocol v7 accepts. Tuple representation\ndeliberately serializes as the closed ordered arrays `["gateway"]` and\n`["gateway", "pd_router"]` rather than as an open component list.'
        ),
    ]


class HttpActionSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: HttpMethod
    path: str


class Parallelism(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attention: Annotated[
        ParallelismAttention | None, Field(description='Attention-block parallelism.')
    ] = None
    experts: Annotated[
        ParallelismExperts | None, Field(description='MoE expert parallelism.')
    ] = None
    outer: Annotated[
        ParallelismOuter | None,
        Field(
            description='Outer deployment parallelism shared by attention and experts.'
        ),
    ] = None


class ReadinessProbeHttpTargetRegistry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decode_role_value: str
    kind: Literal['http_target_registry'] = 'http_target_registry'
    prefill_bootstrap_port: str
    prefill_role_value: str
    readiness_path: str
    registry_path: str
    target_bootstrap_port_field: str
    target_healthy_field: str
    target_role_field: str
    target_scheme: TargetEndpointScheme
    target_url_field: str
    targets_field: str


class ReadinessProbe(
    RootModel[
        ReadinessProbeHttp
        | ReadinessProbeHttpTargetRegistry
        | ReadinessProbeProcessAlive
    ]
):
    root: Annotated[
        ReadinessProbeHttp
        | ReadinessProbeHttpTargetRegistry
        | ReadinessProbeProcessAlive,
        Field(description='How the control plane decides a process is ready.'),
    ]


class RenderedServeProcessFrontend(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: ProcessSpec
    components: FrontendComponents
    kind: Literal['frontend'] = 'frontend'
    launch_files: list[LaunchFileDeclaration]
    process: str
    process_role: FrontendProcessRole


class RenderedServeProcess(
    RootModel[RenderedServeProcessModelRank | RenderedServeProcessFrontend]
):
    root: Annotated[
        RenderedServeProcessModelRank | RenderedServeProcessFrontend,
        Field(
            description='A rendered process bound to the model-rank or frontend allocation identity\nit was produced for.'
        ),
    ]


class ServeProcessAllocationModelRank(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache: str
    dependencies: list[str] = []
    devices: list[Device]
    effective_parallelism: Parallelism
    effective_settings: dict[str, SettingValue]
    endpoint: EndpointAssignment | None = None
    kind: Literal['model_rank'] = 'model_rank'
    launch: AllocationLaunch
    links: Annotated[list[ServeRoleLink], Field(validate_default=True)] = []
    machine: str
    model_locator: str
    ports: dict[str, EndpointAssignment]
    process: str
    rank: Annotated[int, Field(ge=0)]
    rank_count: Annotated[int, Field(ge=0)]
    render_inputs: Annotated[
        list[SuppliedRenderInput], Field(validate_default=True)
    ] = []
    replica: Annotated[int, Field(ge=0)]
    role: str
    role_kind: ServeRoleKind


class ServeRoleInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: ServeRoleKind
    parallelism: Parallelism
    replica_count: Annotated[int, Field(ge=0)]
    settings: dict[str, SettingValue]


class BenchClientRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    case: BenchCaseInput
    case_budget_seconds: Annotated[
        float,
        Field(
            description='Remaining control-plane case budget when the client is released.'
        ),
    ]
    definition: BenchDefinitionInput
    endpoint: ClientEndpointInput
    model: MeasurementModelInput
    population: BenchPopulationInput | None = None
    protocol_version: ProtocolVersion


class CaptureWindowControlRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    endpoint: CaptureWindowControlEndpoint
    start: HttpActionSpec
    stop: HttpActionSpec


class EndpointRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_completions_path: str
    completions_path: str
    prefix_cache_reset: HttpActionSpec | None = None
    protocol: EndpointProtocol


class EvalClientRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_dir: str
    case_budget_seconds: Annotated[
        float,
        Field(
            description='Remaining control-plane case budget when the client is released.'
        ),
    ]
    definition: EvalDefinitionInput
    endpoint: ClientEndpointInput
    model: MeasurementModelInput
    protocol_version: ProtocolVersion
    workspace_root: str
    workspace_source_exclusions: list[str]


class EvalClientResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: str | None = None
    failure_kind: EvalFailureKind | None = None
    gate: EvalMetricGate | None = None
    metrics: dict[str, float]
    native_command: list[str]
    native_exit_code: int | None = None
    native_timed_out: bool = False
    normalized_metrics: Annotated[
        dict[str, EvalNormalizedMetric], Field(validate_default=True)
    ] = {}
    raw_artifacts: list[RawArtifact]
    schema_version: Annotated[
        int,
        Field(
            description='Result envelope version; clients write `1`. The measurement runtime\nrejects an eval result whose version is not `1`.',
            ge=0,
        ),
    ]
    status: ClientStatus
    trial_summary: EvalTrialSummary | None = None


class GatewayPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backend: str
    co_rendering: FrontendCoRendering
    effective_settings: dict[str, SettingValue]
    endpoint: EndpointRequirement
    implementation: str
    implementation_version: str
    ports: list[str] = []
    readiness: ReadinessProbe
    render_inputs: Annotated[
        list[RenderInputDeclaration], Field(validate_default=True)
    ] = []
    render_source: RenderSource
    targets: list[GatewayTarget]


class PdRouterPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backend: str
    co_rendering: FrontendCoRendering
    decode_role: str
    effective_settings: dict[str, SettingValue]
    handoff: FrontendHandoff
    implementation: str
    implementation_version: str
    policies: PdRoutingPolicies
    ports: list[str] = []
    prefill_role: str
    readiness: ReadinessProbe
    render_inputs: Annotated[
        list[RenderInputDeclaration], Field(validate_default=True)
    ] = []
    render_source: RenderSource
    target_scheme: TargetEndpointScheme


class PlanServeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gateway_backend: str | None = None
    kv_transfer: KvTransferMechanism | None = None
    model: ServeModelInput
    pd_router_backend: str | None = None
    profiling: bool = False
    roles: list[ServeRoleInput]
    topology: ServeTopology


class RenderServeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    integration: IntegrationIdentity
    processes: list[RenderedServeProcess]


class ServeProcessAllocationFrontend(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache: str
    components: FrontendComponents
    dependencies: list[str] = []
    devices: list[Device]
    endpoint: EndpointAssignment
    gateway: GatewayPlan
    kind: Literal['frontend'] = 'frontend'
    launch: AllocationLaunch
    links: Annotated[list[ServeRoleLink], Field(validate_default=True)] = []
    machine: str
    pd_router: PdRouterPlan | None = None
    ports: dict[str, EndpointAssignment]
    process: str
    process_role: FrontendProcessRole
    render_inputs: Annotated[
        list[SuppliedRenderInput], Field(validate_default=True)
    ] = []


class ServeProcessAllocation(
    RootModel[ServeProcessAllocationModelRank | ServeProcessAllocationFrontend]
):
    root: Annotated[
        ServeProcessAllocationModelRank | ServeProcessAllocationFrontend,
        Field(
            description='One concrete process allocation supplied to `RenderServe`. Model-rank and\nprocess-only frontend identities are distinct so a frontend cannot acquire\nmodel coordinates or a model locator by construction.'
        ),
    ]


class ServeRoleResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    declared_replica_count: Annotated[int, Field(ge=0)]
    effective_parallelism: Parallelism
    effective_replica_count: Annotated[int, Field(ge=0)]
    effective_settings: dict[str, SettingValue]
    id: str
    kind: ServeRoleKind
    public_endpoint: Annotated[
        EndpointRequirement | None,
        Field(
            description='The public endpoint contract for a direct `single` Engine. Gateway-\nbacked shapes leave this absent and carry the contract on Gateway.'
        ),
    ] = None
    render_inputs: Annotated[
        list[RenderInputDeclaration], Field(validate_default=True)
    ] = []


class AdapterRequestPlanServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: PlanServeInput
    operation: Literal['plan_serve'] = 'plan_serve'
    protocol_version: ProtocolVersion


class AdapterResultRenderServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Literal['render_serve'] = 'render_serve'
    output: RenderServeResult


class CaptureTargetRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    window_control: CaptureWindowControlRequirement


class RenderServeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allocations: list[ServeProcessAllocation]
    gateway_backend: str | None = None
    kv_transfer: KvTransferMechanism | None = None
    model: ServeModelInput
    pd_router_backend: str | None = None
    profiling: bool = False
    topology: ServeTopology


class ServeReplicaRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capture_target: CaptureTargetRequirement | None = None
    device_count: Annotated[int, Field(ge=0)]
    id: str
    ports: list[str]
    primary_ports: list[str]
    primary_readiness: ReadinessProbe
    replica_index: Annotated[int, Field(ge=0)]
    role_id: str
    worker_readiness: ReadinessProbe


class AdapterRequestRenderServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: RenderServeInput
    operation: Literal['render_serve'] = 'render_serve'
    protocol_version: ProtocolVersion


class AdapterRequest(RootModel[AdapterRequestPlanServe | AdapterRequestRenderServe]):
    root: Annotated[
        AdapterRequestPlanServe | AdapterRequestRenderServe,
        Field(
            description='The one JSON request an integration reads from stdin, tagged by the\nrequested operation.'
        ),
    ]


class PlanServeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gateway: GatewayPlan | None = None
    integration: IntegrationIdentity
    links: list[ServeRoleLink]
    pd_router: PdRouterPlan | None = None
    replicas: list[ServeReplicaRequirement]
    roles: list[ServeRoleResult]


class AdapterResultPlanServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Literal['plan_serve'] = 'plan_serve'
    output: PlanServeResult


class AdapterResult(RootModel[AdapterResultPlanServe | AdapterResultRenderServe]):
    root: Annotated[
        AdapterResultPlanServe | AdapterResultRenderServe,
        Field(
            description='The successful result of an [`AdapterRequest`], tagged by the operation it\nanswers.'
        ),
    ]


class AdapterResponseOk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: ProtocolVersion
    result: AdapterResult
    status: Literal['ok'] = 'ok'


class AdapterResponse(RootModel[AdapterResponseOk | AdapterResponseError]):
    root: Annotated[
        AdapterResponseOk | AdapterResponseError,
        Field(
            description='The one JSON response an integration writes to stdout, tagged by outcome.'
        ),
    ]


class AdapterProtocol(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bench_client_request: BenchClientRequest | None = None
    bench_client_result: BenchClientResult | None = None
    bench_dataset_preparation_request: BenchDatasetPreparationRequest | None = None
    bench_dataset_preparation_result: BenchDatasetPreparationResult | None = None
    eval_client_request: EvalClientRequest | None = None
    eval_client_result: EvalClientResult | None = None
    request: AdapterRequest
    response: AdapterResponse


SettingValue.model_rebuild()
