# Rust wire source: crates/inferlab-protocol/src/wire.rs
# @generated by datamodel-codegen:
#   filename:  adapter-protocol-v9.schema.json

from enum import StrEnum
from typing import Annotated, Any, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AdapterErrorCode(StrEnum):
    invalid_request = 'invalid_request'
    unsupported_protocol_version = 'unsupported_protocol_version'
    invalid_settings = 'invalid_settings'
    internal = 'internal'
    unsupported_operation = 'unsupported_operation'


class AllocationLaunchLocal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['local'] = 'local'


class AllocationLaunchSsh(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ssh'] = 'ssh'
    target: str


class AllocationLaunch(RootModel[AllocationLaunchLocal | AllocationLaunchSsh]):
    root: Annotated[
        AllocationLaunchLocal | AllocationLaunchSsh,
        Field(
            description='The machine-local launch channel selected by the control plane.'
        ),
    ]


class CaptureMechanism(StrEnum):
    managed_collection = 'managed_collection'
    engine_trace = 'engine_trace'


class CaptureWindowControlEndpoint(StrEnum):
    replica_entry = 'replica_entry'
    gateway = 'gateway'


class EndpointAssignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    host: str
    port: Annotated[int, Field(ge=0, le=65535)]


class EndpointProtocol(RootModel[Literal['http']]):
    root: Annotated[
        Literal['http'],
        Field(description='The application protocol a workload endpoint speaks.'),
    ] = 'http'


class FrontendGatewayComponent(RootModel[Literal['gateway']]):
    root: Annotated[
        Literal['gateway'],
        Field(
            description='The literal first member of every closed frontend component binding.'
        ),
    ] = 'gateway'


class FrontendHandoff(RootModel[Literal['in_process']]):
    root: Annotated[
        Literal['in_process'],
        Field(
            description='The currently demonstrated Gateway-to-P/D Router handoff is internal to\none fused frontend process.'
        ),
    ] = 'in_process'


class FrontendPdRouterComponent(RootModel[Literal['pd_router']]):
    root: Annotated[
        Literal['pd_router'],
        Field(
            description='The literal second member of the fused P/D frontend component binding.'
        ),
    ] = 'pd_router'


class FrontendProcessRole(RootModel[Literal['gateway']]):
    root: Annotated[
        Literal['gateway'],
        Field(
            description='The one canonical process role available to a protocol-v9 frontend.'
        ),
    ] = 'gateway'


class GatewayFrontendBinding(RootModel[list[FrontendGatewayComponent]]):
    root: Annotated[
        list[FrontendGatewayComponent],
        Field(
            description='The stable schema branch for a Gateway-only frontend binding.',
            max_length=1,
            min_length=1,
        ),
    ]


class GatewayPdRouterFrontendBinding(
    RootModel[tuple[FrontendGatewayComponent, FrontendPdRouterComponent]]
):
    root: Annotated[
        tuple[FrontendGatewayComponent, FrontendPdRouterComponent],
        Field(
            description='The stable schema branch for a fused Gateway and P/D Router binding.'
        ),
    ]


class GatewayTargetEngine(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['engine'] = 'engine'
    role: str


class GatewayTargetPdRouter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['pd_router'] = 'pd_router'


class GatewayTarget(RootModel[GatewayTargetEngine | GatewayTargetPdRouter]):
    root: Annotated[
        GatewayTargetEngine | GatewayTargetPdRouter,
        Field(description='The target a Gateway forwards accepted public requests to.'),
    ]


class HttpMethod(RootModel[Literal['post']]):
    root: Annotated[
        Literal['post'],
        Field(description='The HTTP method of an action specification.'),
    ] = 'post'


class IntegrationIdentity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    adapter_id: str
    adapter_version: str
    framework: str
    framework_version: str


class KvTransferMechanism(StrEnum):
    mooncake = 'mooncake'
    nixl = 'nixl'


class LaunchFileDeclaration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    relative_path: str
    sha256: str
    text: str


class ParallelismAttention(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    context_parallel_size: Annotated[int | None, Field(ge=1)] = None
    data_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ParallelismExperts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    data_parallel_size: Annotated[int | None, Field(ge=1)] = None
    dense_tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None
    expert_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class ParallelismOuter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pipeline_parallel_size: Annotated[int | None, Field(ge=1)] = None
    tensor_parallel_size: Annotated[int | None, Field(ge=1)] = None


class PdRoutingPolicies(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decode: str
    prefill: str


class ProcessSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argv: list[str]
    env: dict[str, str]


class PromptCacheReadZeroRepresentation(StrEnum):
    explicit = 'explicit'
    omitted = 'omitted'


class ProtocolVersion(RootModel[Literal['9']]):
    root: Annotated[
        Literal['9'],
        Field(
            description='The shared protocol version used by framework integrations and release-owned\nmeasurement clients. The only accepted value is `9` (serialized as the\nstring `"9"`); a mismatch is rejected before lowering.'
        ),
    ] = '9'


class ReadinessProbeHttp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['http'] = 'http'
    path: str


class ReadinessProbeProcessAlive(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['process_alive'] = 'process_alive'


class RenderInputDeclaration(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_path: str


class RenderSource(StrEnum):
    control_plane = 'control_plane'
    integration = 'integration'


class RenderedServeProcessModelRank(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: ProcessSpec
    kind: Literal['model_rank'] = 'model_rank'
    launch_files: list[LaunchFileDeclaration]
    process: str
    rank: Annotated[int, Field(ge=0)]
    rank_count: Annotated[int, Field(ge=0)]
    replica: Annotated[int, Field(ge=0)]
    role: str


class ServeModelInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    served_name: str


class Device(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class ServeRoleKind(StrEnum):
    serve = 'serve'
    prefill = 'prefill'
    decode = 'decode'


class ServeRoleLinkRequestRouting(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['request_routing'] = 'request_routing'
    source: str
    targets: list[str]


class ServeRoleLinkKvTransfer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['kv_transfer'] = 'kv_transfer'
    mechanism: KvTransferMechanism
    source: str
    target: str


class ServeRoleLinkBootstrap(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['bootstrap'] = 'bootstrap'
    port: str
    source: str
    target: str


class ServeRoleLinkSideChannel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['side_channel'] = 'side_channel'
    port: str
    source: str
    target: str


class ServeRoleLink(
    RootModel[
        ServeRoleLinkRequestRouting
        | ServeRoleLinkKvTransfer
        | ServeRoleLinkBootstrap
        | ServeRoleLinkSideChannel
    ]
):
    root: Annotated[
        ServeRoleLinkRequestRouting
        | ServeRoleLinkKvTransfer
        | ServeRoleLinkBootstrap
        | ServeRoleLinkSideChannel,
        Field(
            description='A directed link between serve roles the integration declares as part of the\ntopology.'
        ),
    ]


class ServeTopology(StrEnum):
    single = 'single'
    prefill_decode = 'prefill_decode'


class ServerMetricsEndpointRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: str
    port: str | None = None


class SettingValue(
    RootModel[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]]
    ]
):
    root: Annotated[
        Union[bool, int, float, str, list["SettingValue"], dict[str, "SettingValue"]],
        Field(
            description='A framework-specific server setting value carried as structured JSON data\n(never a pre-rendered shell fragment) across the integration boundary.'
        ),
    ]


class SuppliedRenderInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sha256: str
    source_path: str
    text: str


class SyntheticAcceptanceCurveInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    model_key: str
    sha256: Annotated[
        str,
        Field(
            description='The SHA-256 digest of the curve file bytes, verified by the control\nplane against the declaration.'
        ),
    ]
    text: Annotated[
        str, Field(description='The complete digest-verified curve file text.')
    ]
    thinking_mode: Annotated[
        str | None,
        Field(
            description='The effective thinking mode: the declared mode, or `thinking_on` when\nthe declaration omits it and the model entry uses the thinking-mode\nshape. Absent when the model entry is a flat list (no mode applies).'
        ),
    ] = None


class Explicit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptance_length: Annotated[
        float, Field(description='The declared mean acceptance length.')
    ]


class SyntheticAcceptanceInput1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    explicit: Explicit


class SyntheticAcceptanceInput2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    curve: SyntheticAcceptanceCurveInput


class SyntheticAcceptanceInput(
    RootModel[SyntheticAcceptanceInput1 | SyntheticAcceptanceInput2]
):
    root: Annotated[
        SyntheticAcceptanceInput1 | SyntheticAcceptanceInput2,
        Field(
            description="The synthetic acceptance declaration carried to the selected integration\n([[RFC-0003:C-SERVE-SYNTHETIC-ACCEPTANCE]]): exactly one of the explicit\nacceptance length or the digest-verified golden curve with its lookup\ncoordinates. The draft count is not declared; the integration determines\nit from the operator's speculative configuration ([[ADR-0043]])."
        ),
    ]


class SyntheticAcceptanceOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    acceptance_length: Annotated[
        float,
        Field(
            description='The effective acceptance length the integration resolved and overlaid.'
        ),
    ]
    draft_count: Annotated[
        int | None,
        Field(
            description="The draft count the integration determined from the operator's\nspeculative configuration; present for the curve form, absent for the\nexplicit form.",
            ge=0,
        ),
    ] = None


class TargetEndpointScheme(StrEnum):
    http = 'http'
    grpc = 'grpc'


class AdapterError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: AdapterErrorCode
    message: str


class AdapterResponseError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: AdapterError
    protocol_version: ProtocolVersion
    status: Literal['error'] = 'error'


class CaptureWindowHttpActionSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    body: dict[str, Any] | None = None
    method: HttpMethod
    path: str


class FrontendCoRendering(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    process_role: FrontendProcessRole


class FrontendComponents(
    RootModel[GatewayFrontendBinding | GatewayPdRouterFrontendBinding]
):
    root: Annotated[
        GatewayFrontendBinding | GatewayPdRouterFrontendBinding,
        Field(
            description='The only two frontend bindings protocol v9 accepts. Tuple representation\ndeliberately serializes as the closed ordered arrays `["gateway"]` and\n`["gateway", "pd_router"]` rather than as an open component list.'
        ),
    ]


class HttpActionSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    method: HttpMethod
    path: str


class Parallelism(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attention: Annotated[
        ParallelismAttention | None, Field(description='Attention-block parallelism.')
    ] = None
    experts: Annotated[
        ParallelismExperts | None, Field(description='MoE expert parallelism.')
    ] = None
    outer: Annotated[
        ParallelismOuter | None,
        Field(
            description='Outer deployment parallelism shared by attention and experts.'
        ),
    ] = None


class ReadinessProbeHttpTargetRegistry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    decode_role_value: str
    kind: Literal['http_target_registry'] = 'http_target_registry'
    prefill_bootstrap_port: str
    prefill_role_value: str
    readiness_path: str
    registry_path: str
    target_bootstrap_port_field: str
    target_healthy_field: str
    target_role_field: str
    target_scheme: TargetEndpointScheme
    target_url_field: str
    targets_field: str


class ReadinessProbe(
    RootModel[
        ReadinessProbeHttp
        | ReadinessProbeHttpTargetRegistry
        | ReadinessProbeProcessAlive
    ]
):
    root: Annotated[
        ReadinessProbeHttp
        | ReadinessProbeHttpTargetRegistry
        | ReadinessProbeProcessAlive,
        Field(description='How the control plane decides a process is ready.'),
    ]


class RenderedServeProcessFrontend(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    command: ProcessSpec
    components: FrontendComponents
    kind: Literal['frontend'] = 'frontend'
    launch_files: list[LaunchFileDeclaration]
    process: str
    process_role: FrontendProcessRole


class RenderedServeProcess(
    RootModel[RenderedServeProcessModelRank | RenderedServeProcessFrontend]
):
    root: Annotated[
        RenderedServeProcessModelRank | RenderedServeProcessFrontend,
        Field(
            description='A rendered process bound to the model-rank or frontend allocation identity\nit was produced for.'
        ),
    ]


class ServeProcessAllocationModelRank(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache: str
    capture_storage: Annotated[
        str | None,
        Field(
            description='The control-plane-assigned persistent trace directory; present\nonly when this rank belongs to an engine-trace capture target\n([[RFC-0004:C-WORKLOAD-PROFILING]]).'
        ),
    ] = None
    dependencies: list[str] = []
    devices: list[Device]
    effective_parallelism: Parallelism
    effective_settings: dict[str, SettingValue]
    endpoint: EndpointAssignment | None = None
    kind: Literal['model_rank'] = 'model_rank'
    launch: AllocationLaunch
    links: Annotated[list[ServeRoleLink], Field(validate_default=True)] = []
    machine: str
    model_locator: str
    ports: dict[str, EndpointAssignment]
    process: str
    rank: Annotated[int, Field(ge=0)]
    rank_count: Annotated[int, Field(ge=0)]
    render_inputs: Annotated[
        list[SuppliedRenderInput], Field(validate_default=True)
    ] = []
    replica: Annotated[int, Field(ge=0)]
    role: str
    role_kind: ServeRoleKind


class ServeRoleInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    kind: ServeRoleKind
    parallelism: Parallelism
    replica_count: Annotated[int, Field(ge=0)]
    settings: dict[str, SettingValue]


class CaptureWindowControlRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    endpoint: CaptureWindowControlEndpoint
    start: CaptureWindowHttpActionSpec
    stop: CaptureWindowHttpActionSpec


class EndpointRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chat_completions_path: str
    completions_path: str
    prefix_cache_conditioning: Annotated[
        HttpActionSpec | None,
        Field(
            description='A Gateway-backend conditioning fan-out action: the frontend routes one\nconditioning request per prefill replica and attention data-parallel\nrank ([[RFC-0004:C-BENCH-CACHE-STATE]]).'
        ),
    ] = None
    prefix_cache_reset: HttpActionSpec | None = None
    prompt_cache_read_zero_representation: PromptCacheReadZeroRepresentation | None = (
        None
    )
    protocol: EndpointProtocol
    server_metrics: ServerMetricsEndpointRequirement | None = None


class GatewayPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backend: str
    co_rendering: FrontendCoRendering
    effective_settings: dict[str, SettingValue]
    endpoint: EndpointRequirement
    implementation: str
    implementation_version: str
    ports: list[str] = []
    readiness: ReadinessProbe
    render_inputs: Annotated[
        list[RenderInputDeclaration], Field(validate_default=True)
    ] = []
    render_source: RenderSource
    targets: list[GatewayTarget]


class PdRouterPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    backend: str
    co_rendering: FrontendCoRendering
    decode_role: str
    effective_settings: dict[str, SettingValue]
    handoff: FrontendHandoff
    implementation: str
    implementation_version: str
    policies: PdRoutingPolicies
    ports: list[str] = []
    prefill_role: str
    readiness: ReadinessProbe
    render_inputs: Annotated[
        list[RenderInputDeclaration], Field(validate_default=True)
    ] = []
    render_source: RenderSource
    target_scheme: TargetEndpointScheme


class PlanServeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gateway_backend: str | None = None
    kv_transfer: KvTransferMechanism | None = None
    model: ServeModelInput
    pd_router_backend: str | None = None
    profiling: Annotated[
        CaptureMechanism | None,
        Field(
            description='The effective capture mechanism when profiling is requested; absent\nmeans no profiling ([[RFC-0004:C-WORKLOAD-PROFILING]]).'
        ),
    ] = None
    roles: list[ServeRoleInput]
    synthetic_acceptance: Annotated[
        SyntheticAcceptanceInput | None,
        Field(
            description='The synthetic acceptance declaration when the serve declaration\ncarries one ([[RFC-0003:C-SERVE-SYNTHETIC-ACCEPTANCE]]).'
        ),
    ] = None
    topology: ServeTopology


class RenderServeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    integration: IntegrationIdentity
    processes: list[RenderedServeProcess]


class ServeProcessAllocationFrontend(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cache: str
    components: FrontendComponents
    dependencies: list[str] = []
    devices: list[Device]
    endpoint: EndpointAssignment
    gateway: GatewayPlan
    kind: Literal['frontend'] = 'frontend'
    launch: AllocationLaunch
    links: Annotated[list[ServeRoleLink], Field(validate_default=True)] = []
    machine: str
    pd_router: PdRouterPlan | None = None
    ports: dict[str, EndpointAssignment]
    process: str
    process_role: FrontendProcessRole
    render_inputs: Annotated[
        list[SuppliedRenderInput], Field(validate_default=True)
    ] = []


class ServeProcessAllocation(
    RootModel[ServeProcessAllocationModelRank | ServeProcessAllocationFrontend]
):
    root: Annotated[
        ServeProcessAllocationModelRank | ServeProcessAllocationFrontend,
        Field(
            description='One concrete process allocation supplied to `RenderServe`. Model-rank and\nprocess-only frontend identities are distinct so a frontend cannot acquire\nmodel coordinates or a model locator by construction.'
        ),
    ]


class ServeRoleResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    declared_replica_count: Annotated[int, Field(ge=0)]
    effective_parallelism: Parallelism
    effective_replica_count: Annotated[int, Field(ge=0)]
    effective_settings: dict[str, SettingValue]
    id: str
    kind: ServeRoleKind
    public_endpoint: Annotated[
        EndpointRequirement | None,
        Field(
            description='The public endpoint contract for a direct `single` Engine. Gateway-\nbacked shapes leave this absent and carry the contract on Gateway.'
        ),
    ] = None
    render_inputs: Annotated[
        list[RenderInputDeclaration], Field(validate_default=True)
    ] = []


class AdapterRequestPlanServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: PlanServeInput
    operation: Literal['plan_serve'] = 'plan_serve'
    protocol_version: ProtocolVersion


class AdapterResultRenderServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Literal['render_serve'] = 'render_serve'
    output: RenderServeResult


class CaptureTargetRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mechanism: Annotated[
        CaptureMechanism,
        Field(
            description='The capture mechanism this target declares; it must equal the\neffective mechanism requested on the plan.'
        ),
    ]
    window_control: CaptureWindowControlRequirement


class RenderServeInput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allocations: list[ServeProcessAllocation]
    gateway_backend: str | None = None
    kv_transfer: KvTransferMechanism | None = None
    model: ServeModelInput
    pd_router_backend: str | None = None
    profiling: Annotated[
        CaptureMechanism | None,
        Field(
            description='The effective capture mechanism when profiling is requested; absent\nmeans no profiling ([[RFC-0004:C-WORKLOAD-PROFILING]]).'
        ),
    ] = None
    synthetic_acceptance: Annotated[
        SyntheticAcceptanceInput | None,
        Field(
            description='The synthetic acceptance declaration when the serve declaration\ncarries one ([[RFC-0003:C-SERVE-SYNTHETIC-ACCEPTANCE]]).'
        ),
    ] = None
    topology: ServeTopology


class ServeReplicaRequirement(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    capture_target: CaptureTargetRequirement | None = None
    device_count: Annotated[int, Field(ge=0)]
    id: str
    ports: list[str]
    primary_ports: list[str]
    primary_readiness: ReadinessProbe
    replica_index: Annotated[int, Field(ge=0)]
    role_id: str
    worker_readiness: ReadinessProbe


class AdapterRequestRenderServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    input: RenderServeInput
    operation: Literal['render_serve'] = 'render_serve'
    protocol_version: ProtocolVersion


class AdapterRequest(RootModel[AdapterRequestPlanServe | AdapterRequestRenderServe]):
    root: Annotated[
        AdapterRequestPlanServe | AdapterRequestRenderServe,
        Field(
            description='The one JSON request an integration reads from stdin, tagged by the\nrequested operation.'
        ),
    ]


class PlanServeResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    gateway: GatewayPlan | None = None
    integration: IntegrationIdentity
    links: list[ServeRoleLink]
    pd_router: PdRouterPlan | None = None
    replicas: list[ServeReplicaRequirement]
    roles: list[ServeRoleResult]
    synthetic_acceptance: Annotated[
        SyntheticAcceptanceOutcome | None,
        Field(
            description='The resolved synthetic acceptance outcome; required in the accepted\nplan whenever the request carried the declaration, and forbidden\notherwise ([[RFC-0003:C-SERVE-SYNTHETIC-ACCEPTANCE]]).'
        ),
    ] = None


class AdapterResultPlanServe(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    operation: Literal['plan_serve'] = 'plan_serve'
    output: PlanServeResult


class AdapterResult(RootModel[AdapterResultPlanServe | AdapterResultRenderServe]):
    root: Annotated[
        AdapterResultPlanServe | AdapterResultRenderServe,
        Field(
            description='The successful result of an [`AdapterRequest`], tagged by the operation it\nanswers.'
        ),
    ]


class AdapterResponseOk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    protocol_version: ProtocolVersion
    result: AdapterResult
    status: Literal['ok'] = 'ok'


class AdapterResponse(RootModel[AdapterResponseOk | AdapterResponseError]):
    root: Annotated[
        AdapterResponseOk | AdapterResponseError,
        Field(
            description='The one JSON response an integration writes to stdout, tagged by outcome.'
        ),
    ]


class AdapterProtocol(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    request: AdapterRequest
    response: AdapterResponse


SettingValue.model_rebuild()
